-- =====================================================================
-- AzTU — CONSOLIDATED PRODUCTION MIGRATION
--
-- Covers everything added in this batch:
--   * cafedra scientific activity (6 sections + publications with year)
--   * RBAC (roles, permissions, role_permissions)
--   * admin activity log
--   * admin user display name + profile image
--
-- Run the whole file in ONE psql session:
--     psql "$DATABASE_URL" -f migrations_prod_consolidated.sql
--
-- Every statement is idempotent — safe to re-run. Additive only: it adds
-- tables and columns and never drops or rewrites existing data.
-- Take a snapshot first anyway.
--
-- STEP 4 seeds the super admin. Edit the username/hash there before running.
-- =====================================================================


-- =====================================================================
-- STEP 1 — SCHEMA
-- =====================================================================
-- ---------------------------------------------------------------------
-- CAFEDRA SCIENTIFIC ACTIVITY
-- ---------------------------------------------------------------------

alter table cafedras_tr add column if not exists research_areas_intro text;
alter table cafedras_tr add column if not exists projects_grants_intro text;
alter table cafedras_tr add column if not exists publications_intro text;
alter table cafedras_tr add column if not exists industry_cooperation_intro text;
alter table cafedras_tr add column if not exists international_cooperation_intro text;

alter table cafedra_projects add column if not exists url varchar(1024);

alter table cafedra_partner_companies add column if not exists logo_url varchar(1024);
alter table cafedra_partner_companies add column if not exists website_url varchar(1024);

create table if not exists cafedra_scientific_publications (
    id integer primary key,
    cafedra_code varchar(50) not null references cafedras(cafedra_code) on delete cascade,
    publication_index varchar(50) not null,
    quartile varchar(5),
    published_at varchar(50),
    year integer,
    url varchar(2048),
    display_order integer not null default 0,
    created_at timestamptz not null,
    updated_at timestamptz
);

alter table cafedra_scientific_publications add column if not exists year integer;

create index if not exists ix_cafedra_scientific_publications_cafedra_code
    on cafedra_scientific_publications (cafedra_code);

create index if not exists ix_cafedra_scientific_publications_year
    on cafedra_scientific_publications (cafedra_code, year desc, display_order);

create table if not exists cafedra_scientific_publication_tr (
    id integer primary key,
    publication_id integer not null references cafedra_scientific_publications(id) on delete cascade,
    lang_code varchar(10) not null,
    title varchar(1000) not null,
    authors text,
    journal text,
    country varchar(255),
    created_at timestamptz not null,
    updated_at timestamptz,
    constraint uq_cafedra_scientific_publication_tr_id_lang unique (publication_id, lang_code)
);




-- ═══════════════════════════════════════════════════════════════════════════
-- RBAC + admin activity log
-- ═══════════════════════════════════════════════════════════════════════════

create table if not exists roles (
    id          integer generated by default as identity primary key,
    code        varchar(50)  not null unique,
    name_az     varchar(100) not null,
    name_en     varchar(100) not null,
    description text,
    is_system   boolean      not null default false,
    created_at  timestamptz  not null default current_timestamp,
    updated_at  timestamptz
);
create index if not exists ix_roles_code on roles (code);

create table if not exists permissions (
    id         integer generated by default as identity primary key,
    key        varchar(100) not null unique,
    domain     varchar(50)  not null,
    action     varchar(50)  not null,
    label_az   varchar(200) not null,
    label_en   varchar(200) not null,
    created_at timestamptz  not null default current_timestamp
);
create index if not exists ix_permissions_domain on permissions (domain);

create table if not exists role_permissions (
    role_id       integer not null references roles(id)       on delete cascade,
    permission_id integer not null references permissions(id) on delete cascade,
    granted_at    timestamptz not null default current_timestamp,
    primary key (role_id, permission_id)
);
create index if not exists ix_role_permissions_permission on role_permissions (permission_id);

alter table admin_users add column if not exists role_id integer;
do $$ begin
    alter table admin_users
        add constraint fk_admin_users_role
        foreign key (role_id) references roles(id) on delete restrict;
exception when duplicate_object then null; end $$;
create index if not exists ix_admin_users_role_id on admin_users (role_id);

-- admin_users.id is `integer primary key` with NO identity in the schema of
-- record. POST /api/admin-users does INSERT ... RETURNING id and WILL fail on a
-- null PK until this runs. Idempotent; safe to re-run.
do $$
declare seq text;
begin
    if (select is_identity from information_schema.columns
        where table_schema='public' and table_name='admin_users' and column_name='id') = 'NO' then
        alter table admin_users alter column id drop default;
        alter table admin_users alter column id add generated by default as identity;
        seq := pg_get_serial_sequence('public.admin_users', 'id');
        perform setval(seq, coalesce((select max(id) from admin_users), 0) + 1, false);
    end if;
end $$;

create table if not exists admin_activity_log (
    id             bigint generated by default as identity primary key,
    admin_user_id  integer references admin_users(id) on delete set null,
    admin_username varchar(50)  not null,
    action_key     varchar(100) not null,
    domain         varchar(50)  not null,
    method         varchar(10)  not null,
    path           text         not null,
    route_template text,
    target_type    varchar(50),
    target_id      text,
    target_label   text,
    status_code    integer      not null,
    outcome        varchar(20)  not null default 'success',
    ip             varchar(45),
    user_agent     text,
    request_id     varchar(36),
    meta           jsonb,
    created_at     timestamptz  not null default current_timestamp
);
create index if not exists ix_activity_created_at    on admin_activity_log (created_at desc);
create index if not exists ix_activity_admin_created on admin_activity_log (admin_user_id, created_at desc);
create index if not exists ix_activity_action        on admin_activity_log (action_key);
create index if not exists ix_activity_domain        on admin_activity_log (domain);
create index if not exists ix_activity_target        on admin_activity_log (target_type, target_id);

-- Optional display identity for admin users. Existing rows keep NULLs; every
-- screen falls back to the username. profile_image is written only by
-- PUT /api/admin-users/{user_id}/profile-image.
alter table admin_users add column if not exists first_name    varchar(100);
alter table admin_users add column if not exists last_name     varchar(100);
alter table admin_users add column if not exists profile_image varchar(1024);

-- Usernames are AzTU email addresses, which do not fit in varchar(50).
-- Widening is safe: no existing value can be too long for the new type, and
-- re-running is a no-op because the column is already varchar(255).
alter table admin_users        alter column username       type varchar(255);
alter table admin_activity_log alter column admin_username type varchar(255);


-- =====================================================================
-- STEP 2 — IDENTITY / SEQUENCES
--
-- Older tables declare `id integer primary key` with no identity, so
-- INSERT ... RETURNING id writes a null PK and fails. This is what broke
-- POST /api/cafedra/{code}/publications in production.
-- New tables in STEP 1 declare identity inline and do not need this, but
-- running it is harmless — it only touches columns where is_identity='NO'.
-- =====================================================================
-- Adds GENERATED BY DEFAULT AS IDENTITY to every `id` column in the public
-- schema that is an integer/bigint primary key and isn't already an identity.
-- Also resyncs the implicit identity sequence to max(id)+1 so future inserts
-- don't collide with rows that were inserted with explicit ids.

do $$
declare
    r record;
    max_id bigint;
    seq_name text;
begin
    for r in
        select c.table_schema,
               c.table_name,
               c.column_name,
               c.data_type
        from information_schema.columns c
        join information_schema.table_constraints tc
          on tc.table_schema = c.table_schema
         and tc.table_name = c.table_name
         and tc.constraint_type = 'PRIMARY KEY'
        join information_schema.key_column_usage kcu
          on kcu.constraint_name = tc.constraint_name
         and kcu.table_schema = tc.table_schema
         and kcu.column_name = c.column_name
        where c.table_schema = 'public'
          and c.column_name = 'id'
          and c.data_type in ('integer', 'bigint')
          and c.is_identity = 'NO'
    loop
        execute format(
            'alter table %I.%I alter column %I drop default',
            r.table_schema, r.table_name, r.column_name
        );

        execute format(
            'alter table %I.%I alter column %I add generated by default as identity',
            r.table_schema, r.table_name, r.column_name
        );

        execute format('select coalesce(max(%I), 0) from %I.%I',
                       r.column_name, r.table_schema, r.table_name)
        into max_id;

        seq_name := pg_get_serial_sequence(
            format('%I.%I', r.table_schema, r.table_name),
            r.column_name
        );

        if seq_name is not null and max_id > 0 then
            execute format('select setval(%L, %s, true)', seq_name, max_id);
        end if;
    end loop;
end $$;


-- =====================================================================
-- STEP 3 — SUPER ADMIN ROLE
--
-- The app's sync_rbac() creates this on boot, but seeding it here lets
-- STEP 4 run in the same session, before the first restart.
-- =====================================================================

insert into roles (code, name_az, name_en, description, is_system)
values ('super_admin', 'Super admin', 'Super admin',
        'Bütün icazələr. Redaktə və silinmə mümkün deyil.', true)
on conflict (code) do update
   set name_az   = excluded.name_az,
       name_en   = excluded.name_en,
       is_system = true;


-- =====================================================================
-- STEP 4 — SUPER ADMIN USER
--
-- The hash is bcrypt, matching app/core/security.py's passlib context.
-- Generate a replacement with:
--   ./venv/bin/python -c "from passlib.context import CryptContext; \
--     print(CryptContext(schemes=['bcrypt']).hash('YOUR-PASSWORD'))"
-- Never put a plaintext password in this file.
-- =====================================================================

insert into admin_users (username, hashed_password, is_active, created_at, role_id)
values (
    'firdovsi.rzaev@aztu.edu.az',
    '$2b$12$spoNTdeTNH/cbK012BknJe79sVQQkJleJwj.T7Uo55jX1Dcolhjfy',
    true,
    current_timestamp,
    (select id from roles where code = 'super_admin')
)
on conflict (username) do update
   set hashed_password = excluded.hashed_password,
       is_active       = true,
       role_id         = excluded.role_id,
       updated_at      = current_timestamp;


-- =====================================================================
-- STEP 5 — VERIFY
-- =====================================================================

-- Every admin and the role they hold. Rows with a null code have NO
-- permissions once PERMISSION_ENFORCEMENT_MODE is flipped to "enforce".
select u.id, u.username, u.is_active, r.code as role_code
from admin_users u
left join roles r on r.id = u.role_id
order by u.id;

-- Should list the 6 new tables.
select table_name
from information_schema.tables
where table_schema = 'public'
  and table_name in ('roles', 'permissions', 'role_permissions',
                     'admin_activity_log',
                     'cafedra_scientific_publications',
                     'cafedra_scientific_publication_tr')
order by table_name;

-- Must return zero rows. Anything here still writes null PKs on insert.
select table_name, column_name
from information_schema.columns
where table_schema = 'public'
  and column_name  = 'id'
  and data_type in ('integer', 'bigint')
  and is_identity  = 'NO';
