-- =====================================================================
-- MIGRATION — Research: "Tədqiqat Prioritetləri" (Priority Research Areas)
--
-- Slugs on the website:
--   az  /az/tedqiqat/tedqiqat-fealiyyeti/tedqiqat-prioritetleri
--   en  /en/research/research-activity/research-priorities
--
-- Creates the Research section's editorial tables, mirroring the About
-- section one for one:
--   research_pages / _tr           → the page and its hero copy
--   research_page_priorities / _tr → the numbered priority cards
--   research_page_links / _tr      → the "Bölmədə daha çox" buttons
--   the `research-priorities` page itself
--
-- Why its own family of tables rather than a row in `about_pages`: the
-- About tables are the About section's, and the two sections will drift
-- (About has documents, pillars and a timeline; Research will grow
-- journals, conferences and grant screens). Sharing them would make
-- every future Research column a nullable About column.
--
-- Why the tables are named `research_page_*` and not `research_*`:
-- `research_projects` and `research_institutes` already exist and are
-- entities, not pages. The prefix keeps the two families apart at a
-- glance.
--
-- Why `vision_html` sits on the page translation: the "Strateji baxış"
-- card is one editor-authored paragraph owned by the page, exactly like
-- the hero's `description`. Its heading is drawn by the website and is
-- therefore not stored.
--
-- What is deliberately NOT here: the eyebrow, the breadcrumb, the card
-- icons and gradients, the counter strip and the SEO tags. The website
-- hard-codes them, so they get no columns.
--
-- Idempotent and additive. Safe to re-run.
-- =====================================================================


-- =====================================================================
-- STEP 1 — SCHEMA
-- =====================================================================
create table if not exists research_pages (
    id            integer generated by default as identity primary key,
    page_key      varchar(100) not null unique,
    -- Which shape this page is; drives the dashboard form and, later, the
    -- website renderer. Today: 'priorities'.
    template      varchar(50)  not null default 'priorities',
    slug_az       varchar(255),
    slug_en       varchar(255),
    display_order integer      not null default 0,
    -- False keeps the page out of the public API while it is being filled in.
    is_active     boolean      not null default false,
    created_at    timestamptz  not null default current_timestamp,
    updated_at    timestamptz
);
create index if not exists ix_research_pages_order
    on research_pages (display_order, id);

create table if not exists research_page_tr (
    id          integer generated by default as identity primary key,
    page_id     integer not null references research_pages(id) on delete cascade,
    lang_code   varchar(10) not null,
    title       varchar(500),
    -- Rich text under the H1 in the hero.
    description text,
    -- Rich text of the "Strateji baxış" intro card.
    vision_html text,
    -- Heading of the "More in this section" block.
    links_title varchar(500),
    created_at  timestamptz not null default current_timestamp,
    updated_at  timestamptz,
    constraint uq_research_page_tr_page_lang unique (page_id, lang_code)
);
create index if not exists ix_research_page_tr_page
    on research_page_tr (page_id, lang_code);

create table if not exists research_page_priorities (
    id            integer generated by default as identity primary key,
    page_id       integer not null references research_pages(id) on delete cascade,
    -- The card's number and icon are read from this position by the website,
    -- which is why the row carries no key of its own.
    display_order integer not null default 0,
    created_at    timestamptz not null default current_timestamp,
    updated_at    timestamptz
);
create index if not exists ix_research_page_priorities_page
    on research_page_priorities (page_id, display_order);

create table if not exists research_page_priority_tr (
    id          integer generated by default as identity primary key,
    priority_id integer not null references research_page_priorities(id) on delete cascade,
    lang_code   varchar(10) not null,
    title       varchar(500),
    description text,
    created_at  timestamptz not null default current_timestamp,
    updated_at  timestamptz,
    constraint uq_research_priority_tr_priority_lang unique (priority_id, lang_code)
);
create index if not exists ix_research_page_priority_tr_priority
    on research_page_priority_tr (priority_id, lang_code);

create table if not exists research_page_links (
    id            integer generated by default as identity primary key,
    page_id       integer not null references research_pages(id) on delete cascade,
    url           varchar(2048),
    display_order integer not null default 0,
    created_at    timestamptz not null default current_timestamp,
    updated_at    timestamptz
);
create index if not exists ix_research_page_links_page
    on research_page_links (page_id, display_order);

create table if not exists research_page_link_tr (
    id         integer generated by default as identity primary key,
    link_id    integer not null references research_page_links(id) on delete cascade,
    lang_code  varchar(10) not null,
    label      varchar(500),
    created_at timestamptz not null default current_timestamp,
    updated_at timestamptz,
    constraint uq_research_page_link_tr_link_lang unique (link_id, lang_code)
);
create index if not exists ix_research_page_link_tr_link
    on research_page_link_tr (link_id, lang_code);


-- =====================================================================
-- STEP 2 — SEED: the Research Priorities page
--
-- Structure and headings only; the copy and the priority cards are
-- entered from the dashboard, and the page stays unpublished until an
-- editor publishes it.
-- =====================================================================
insert into research_pages (page_key, template, slug_az, slug_en, display_order, is_active)
values ('research-priorities', 'priorities',
        'tedqiqat/tedqiqat-fealiyyeti/tedqiqat-prioritetleri',
        'research/research-activity/research-priorities',
        1, false)
on conflict (page_key) do nothing;

insert into research_page_tr (page_id, lang_code, title, links_title)
select p.id, 'az', 'Prioritet Tədqiqat Sahələri', 'Bölmədə daha çox'
from research_pages p where p.page_key = 'research-priorities'
on conflict (page_id, lang_code) do nothing;

insert into research_page_tr (page_id, lang_code, title, links_title)
select p.id, 'en', 'Priority Research Areas', 'More in this section'
from research_pages p where p.page_key = 'research-priorities'
on conflict (page_id, lang_code) do nothing;


-- =====================================================================
-- STEP 3 — VERIFY. Expect research-priorities with template
-- 'priorities', two translation rows and, until an editor saves, zero
-- priority cards.
-- =====================================================================
select p.page_key, p.template, p.is_active,
       (select count(*) from research_page_tr         t where t.page_id = p.id) as translations,
       (select count(*) from research_page_priorities r where r.page_id = p.id) as priorities,
       (select count(*) from research_page_links      l where l.page_id = p.id) as links
from research_pages p
order by p.display_order;
