-- =====================================================================
-- MIGRATION — About: "Strateji İnkişaf Planı" (Strategic Development Plan)
--
-- Adds:
--   about_pages.document_url      → the plan file (uploaded) or a pasted URL
--   about_page_tr.document_label  → the download button's text, per language
--   about_page_tr.pillars_title   → the "Strategic Pillars" heading
--   about_pillars / _tr           → the numbered pillar cards, with tags
--   about_lists / _tr             → a titled list of strings (values, KPIs)
--   the `strategic-plan` page itself
--
-- Why `about_lists` rather than two tables: "Korporativ Dəyərlər" and
-- "Əsas Performans Göstəriciləri" are the same thing — a heading plus an
-- ordered set of one-line entries — differing only in whether the website
-- renders them with bullets or numbers. `style` carries exactly that.
--
-- Why `pillars_title` sits on the page translation: it is a section
-- heading owned by the page, the same as the existing `links_title`.
--
-- Why tags and items are JSONB arrays: they are ordered lists of plain
-- strings with no attributes of their own, so a child table would add
-- two joins and buy nothing an editor can feel.
--
-- Run AFTER migrations_about.sql. Idempotent and additive.
-- =====================================================================


-- =====================================================================
-- STEP 1 — SCHEMA
-- =====================================================================
alter table about_pages
    add column if not exists document_url varchar(2048);

alter table about_page_tr
    add column if not exists document_label varchar(500);
alter table about_page_tr
    add column if not exists pillars_title  varchar(500);

create table if not exists about_pillars (
    id            integer generated by default as identity primary key,
    page_id       integer not null references about_pages(id) on delete cascade,
    display_order integer not null default 0,
    created_at    timestamptz not null default current_timestamp,
    updated_at    timestamptz
);
create index if not exists ix_about_pillars_page
    on about_pillars (page_id, display_order);

create table if not exists about_pillar_tr (
    id          integer generated by default as identity primary key,
    pillar_id   integer not null references about_pillars(id) on delete cascade,
    lang_code   varchar(10) not null,
    title       varchar(500),
    description text,
    -- Ordered list of plain strings: ["Modernized curriculum", ...].
    tags        jsonb,
    created_at  timestamptz not null default current_timestamp,
    updated_at  timestamptz,
    constraint uq_about_pillar_tr_pillar_lang unique (pillar_id, lang_code)
);
create index if not exists ix_about_pillar_tr_pillar
    on about_pillar_tr (pillar_id, lang_code);

create table if not exists about_lists (
    id            integer generated by default as identity primary key,
    page_id       integer not null references about_pages(id) on delete cascade,
    -- Stable identifier: values | kpis.
    list_key      varchar(100) not null,
    -- How the website renders the entries: bullet | number.
    style         varchar(20)  not null default 'bullet',
    display_order integer      not null default 0,
    created_at    timestamptz  not null default current_timestamp,
    updated_at    timestamptz,
    constraint uq_about_lists_page_key unique (page_id, list_key)
);
create index if not exists ix_about_lists_page
    on about_lists (page_id, display_order);

create table if not exists about_list_tr (
    id         integer generated by default as identity primary key,
    list_id    integer not null references about_lists(id) on delete cascade,
    lang_code  varchar(10) not null,
    title      varchar(500),
    -- Ordered list of plain strings, one per rendered line.
    items      jsonb,
    created_at timestamptz not null default current_timestamp,
    updated_at timestamptz,
    constraint uq_about_list_tr_list_lang unique (list_id, lang_code)
);
create index if not exists ix_about_list_tr_list
    on about_list_tr (list_id, lang_code);


-- =====================================================================
-- STEP 2 — SEED: the Strategic Plan page
--
-- Structure only; the copy is entered from the dashboard, and the page
-- stays unpublished until an editor publishes it.
-- =====================================================================
insert into about_pages (page_key, template, slug_az, slug_en, display_order, is_active)
values ('strategic-plan', 'strategic_plan',
        'haqqimizda/vizyon-ve-missiya/strateji-plan',
        'about/vision-mission/strategic-plan',
        3, false)
on conflict (page_key) do nothing;

insert into about_page_tr (page_id, lang_code, title, pillars_title, document_label, links_title)
select p.id, 'az', 'Strateji İnkişaf Planı', 'Strateji Sütunlar', 'Sənədi yüklə', 'Bölmədə daha çox'
from about_pages p where p.page_key = 'strategic-plan'
on conflict (page_id, lang_code) do nothing;

insert into about_page_tr (page_id, lang_code, title, pillars_title, document_label, links_title)
select p.id, 'en', 'Strategic Development Plan', 'Strategic Pillars', 'Download the document', 'More in this section'
from about_pages p where p.page_key = 'strategic-plan'
on conflict (page_id, lang_code) do nothing;

-- The two lists the page renders, in order.
insert into about_lists (page_id, list_key, style, display_order)
select p.id, v.k, v.style, v.o
from about_pages p
cross join (values ('values', 'bullet', 1), ('kpis', 'number', 2)) as v(k, style, o)
where p.page_key = 'strategic-plan'
on conflict (page_id, list_key) do nothing;

insert into about_list_tr (list_id, lang_code, title)
select l.id, v.lang, v.title
from about_lists l
join about_pages p on p.id = l.page_id
join (values ('values', 'az', 'Korporativ Dəyərlər'),
             ('values', 'en', 'Core Values'),
             ('kpis',   'az', 'Əsas Performans Göstəriciləri (KPI)'),
             ('kpis',   'en', 'Major KPIs')
     ) as v(k, lang, title) on v.k = l.list_key
where p.page_key = 'strategic-plan'
on conflict (list_id, lang_code) do nothing;


-- =====================================================================
-- STEP 3 — VERIFY. Expect strategic-plan with template 'strategic_plan'
-- and its two lists.
-- =====================================================================
select p.page_key, p.template, p.is_active,
       (select count(*) from about_lists   l where l.page_id = p.id) as lists,
       (select count(*) from about_pillars r where r.page_id = p.id) as pillars
from about_pages p
order by p.display_order;
