-- =====================================================================
-- PRODUCTION MIGRATION — Cafedra patents (Patentlər)
--
-- Adds the patents section of a cafedra's scientific activity:
--   cafedra_patents      → number, year, url, ordering
--   cafedra_patent_tr    → title + authors, per language
--
-- Run in one psql session. Every statement is idempotent and additive.
-- Follow it with migrations_resync_sequences.sql if you seed rows with
-- explicit ids — seeds do not advance the sequence.
-- =====================================================================


-- =====================================================================
-- STEP 1 — SCHEMA
-- =====================================================================
-- The section's bilingual intro/heading, alongside the other section intros.
alter table cafedras_tr add column if not exists patents_intro text;

create table if not exists cafedra_patents (
    id            integer generated by default as identity primary key,
    cafedra_code  varchar(50) not null references cafedras(cafedra_code) on delete cascade,
    patent_number varchar(100),
    year          integer,
    url           varchar(2048),
    display_order integer not null default 0,
    created_at    timestamptz not null default current_timestamp,
    updated_at    timestamptz
);
create index if not exists ix_cafedra_patents_cafedra_code
    on cafedra_patents (cafedra_code);
-- Matches the read path exactly: newest year first, then authored order.
create index if not exists ix_cafedra_patents_year
    on cafedra_patents (cafedra_code, year desc, display_order);

create table if not exists cafedra_patent_tr (
    id         integer generated by default as identity primary key,
    patent_id  integer not null references cafedra_patents(id) on delete cascade,
    lang_code  varchar(10) not null,
    title      varchar(1000) not null,
    authors    text,
    created_at timestamptz not null default current_timestamp,
    updated_at timestamptz,
    constraint uq_cafedra_patent_tr_id_lang unique (patent_id, lang_code)
);
create index if not exists ix_cafedra_patent_tr_patent_id
    on cafedra_patent_tr (patent_id);


-- =====================================================================
-- STEP 2 — VERIFY
--
-- 2a. Both tables must be listed.
-- 2b. MUST return zero rows: the unique constraint is load-bearing. Without
--     it the serializer's scalar_one_or_none() raises MultipleResultsFound
--     on a duplicate translation and the whole cafedra page 500s.
-- =====================================================================
select table_name
from information_schema.tables
where table_schema = 'public'
  and table_name in ('cafedra_patents', 'cafedra_patent_tr')
order by table_name;

select 'missing unique constraint' as problem
where not exists (
    select 1 from pg_constraint
    where conname = 'uq_cafedra_patent_tr_id_lang'
);
