-- =====================================================================
-- MIGRATION — Management: "Offices and Centres" (Ofis və Mərkəzlər)
--
-- A creatable CRUD entity (not a fixed seeded page): the dashboard adds
-- and removes offices, each generating its own az/en slug from the name.
-- One office carries an About section, goals, core functions, a director
-- (with an education history), a staff roster and contact details.
--
-- Language-neutral facts (slug, phone, e-mail, image, ordering) live on the
-- row; translated text lives on the `*_tr` sibling keyed by lang_code.
--
-- No seed — the seven existing centres are entered from the dashboard.
-- Idempotent and additive.
-- =====================================================================


-- ── offices ──────────────────────────────────────────────────────────
create table if not exists offices (
    id                  integer generated by default as identity primary key,
    slug_az             varchar(255) unique,
    slug_en             varchar(255) unique,
    display_order       integer not null default 0,
    is_active           boolean not null default false,
    -- Director contact (language-neutral).
    director_phone      varchar(100),
    director_phone_code varchar(50),
    director_email      varchar(255),
    director_image_url  varchar(2048),
    -- Office contact (language-neutral).
    contact_phone       varchar(100),
    contact_phone_code  varchar(50),
    contact_email       varchar(255),
    created_at          timestamptz not null default current_timestamp,
    updated_at          timestamptz
);

create table if not exists office_tr (
    id                  integer generated by default as identity primary key,
    office_id           integer not null references offices(id) on delete cascade,
    lang_code           varchar(10) not null,
    name                varchar(500),
    short_description   text,
    about_title         varchar(500),
    about_text          text,
    goal_title          varchar(500),
    goals               jsonb,
    functions_title     varchar(500),
    director_title      varchar(500),
    director_name       varchar(255),
    director_surname    varchar(255),
    director_position   varchar(500),
    director_bio        text,
    director_room       varchar(255),
    director_work_hours varchar(500),
    staff_title         varchar(500),
    contact_room        varchar(255),
    contact_work_hours  varchar(500),
    created_at          timestamptz not null default current_timestamp,
    updated_at          timestamptz,
    constraint uq_office_tr_office_lang unique (office_id, lang_code)
);
create index if not exists ix_office_tr_office on office_tr (office_id, lang_code);


-- ── core functions ───────────────────────────────────────────────────
create table if not exists office_functions (
    id            integer generated by default as identity primary key,
    office_id     integer not null references offices(id) on delete cascade,
    display_order integer not null default 0,
    created_at    timestamptz not null default current_timestamp,
    updated_at    timestamptz
);
create index if not exists ix_office_functions_office
    on office_functions (office_id, display_order);

create table if not exists office_function_tr (
    id          integer generated by default as identity primary key,
    function_id integer not null references office_functions(id) on delete cascade,
    lang_code   varchar(10) not null,
    title       varchar(500),
    description text,
    created_at  timestamptz not null default current_timestamp,
    updated_at  timestamptz,
    constraint uq_office_function_tr_fn_lang unique (function_id, lang_code)
);
create index if not exists ix_office_function_tr_fn
    on office_function_tr (function_id, lang_code);


-- ── director education ───────────────────────────────────────────────
create table if not exists office_educations (
    id            integer generated by default as identity primary key,
    office_id     integer not null references offices(id) on delete cascade,
    start_year    varchar(20),
    end_year      varchar(20),
    display_order integer not null default 0,
    created_at    timestamptz not null default current_timestamp,
    updated_at    timestamptz
);
create index if not exists ix_office_educations_office
    on office_educations (office_id, display_order);

create table if not exists office_education_tr (
    id           integer generated by default as identity primary key,
    education_id integer not null references office_educations(id) on delete cascade,
    lang_code    varchar(10) not null,
    degree       varchar(500),
    university   varchar(500),
    created_at   timestamptz not null default current_timestamp,
    updated_at   timestamptz,
    constraint uq_office_education_tr_edu_lang unique (education_id, lang_code)
);
create index if not exists ix_office_education_tr_edu
    on office_education_tr (education_id, lang_code);


-- ── staff ────────────────────────────────────────────────────────────
create table if not exists office_staff (
    id            integer generated by default as identity primary key,
    office_id     integer not null references offices(id) on delete cascade,
    phone         varchar(100),
    phone_code    varchar(50),
    email         varchar(255),
    image_url     varchar(2048),
    display_order integer not null default 0,
    created_at    timestamptz not null default current_timestamp,
    updated_at    timestamptz
);
create index if not exists ix_office_staff_office
    on office_staff (office_id, display_order);

create table if not exists office_staff_tr (
    id         integer generated by default as identity primary key,
    staff_id   integer not null references office_staff(id) on delete cascade,
    lang_code  varchar(10) not null,
    name       varchar(255),
    surname    varchar(255),
    duty       varchar(500),
    created_at timestamptz not null default current_timestamp,
    updated_at timestamptz,
    constraint uq_office_staff_tr_staff_lang unique (staff_id, lang_code)
);
create index if not exists ix_office_staff_tr_staff
    on office_staff_tr (staff_id, lang_code);


-- ── VERIFY ───────────────────────────────────────────────────────────
select count(*) as office_tables
from information_schema.tables
where table_name in (
    'offices','office_tr','office_functions','office_function_tr',
    'office_educations','office_education_tr','office_staff','office_staff_tr'
);
