-- =====================================================================
-- MIGRATION — About section ("Haqqımızda")
--
-- Six tables, matching the page exactly:
--
--   about_pages     → one row per About screen (slug, publish flag)
--   about_page_tr   → hero title + short description, per language
--   about_blocks    → the statement cards (Mission / Vision / Goal)
--   about_block_tr  → each card's heading and body, per language
--   about_links     → the "More in this section" buttons
--   about_link_tr   → each button's label, per language
--
-- Language-neutral facts (a slug, a URL, an order) live on the row;
-- anything a translator touches lives on the `*_tr` sibling.
--
-- The hero video, the card icons and the page's SEO tags are NOT here:
-- they are hard-coded in the website by design.
--
-- Run in one psql session. Every statement is idempotent and additive,
-- so re-running it never disturbs copy an editor has already entered.
-- =====================================================================


-- =====================================================================
-- STEP 1 — SCHEMA
-- =====================================================================
create table if not exists about_pages (
    id            integer generated by default as identity primary key,
    page_key      varchar(100) not null unique,
    slug_az       varchar(255),
    slug_en       varchar(255),
    display_order integer      not null default 0,
    -- False keeps the page out of the public API while it is being filled
    -- in, so production never shows a half-written screen.
    is_active     boolean      not null default false,
    created_at    timestamptz  not null default current_timestamp,
    updated_at    timestamptz
);
create index if not exists ix_about_pages_order on about_pages (display_order, id);

create table if not exists about_page_tr (
    id          integer generated by default as identity primary key,
    page_id     integer not null references about_pages(id) on delete cascade,
    lang_code   varchar(10) not null,
    -- The H1 in the hero.
    title       varchar(500),
    -- Rich text, shown under the H1.
    description text,
    -- Heading of the "More in this section" block.
    links_title varchar(500),
    created_at  timestamptz not null default current_timestamp,
    updated_at  timestamptz,
    constraint uq_about_page_tr_page_lang unique (page_id, lang_code)
);
create index if not exists ix_about_page_tr_page on about_page_tr (page_id, lang_code);

create table if not exists about_blocks (
    id            integer generated by default as identity primary key,
    page_id       integer not null references about_pages(id) on delete cascade,
    -- Stable identifier the website maps to an icon: mission | vision | goal.
    block_key     varchar(100) not null,
    display_order integer not null default 0,
    created_at    timestamptz not null default current_timestamp,
    updated_at    timestamptz,
    constraint uq_about_blocks_page_key unique (page_id, block_key)
);
create index if not exists ix_about_blocks_page on about_blocks (page_id, display_order);

create table if not exists about_block_tr (
    id         integer generated by default as identity primary key,
    block_id   integer not null references about_blocks(id) on delete cascade,
    lang_code  varchar(10) not null,
    title      varchar(500),
    body       text,
    created_at timestamptz not null default current_timestamp,
    updated_at timestamptz,
    constraint uq_about_block_tr_block_lang unique (block_id, lang_code)
);
create index if not exists ix_about_block_tr_block on about_block_tr (block_id, lang_code);

create table if not exists about_links (
    id            integer generated by default as identity primary key,
    page_id       integer not null references about_pages(id) on delete cascade,
    url           varchar(2048),
    display_order integer not null default 0,
    created_at    timestamptz not null default current_timestamp,
    updated_at    timestamptz
);
create index if not exists ix_about_links_page on about_links (page_id, display_order);

create table if not exists about_link_tr (
    id         integer generated by default as identity primary key,
    link_id    integer not null references about_links(id) on delete cascade,
    lang_code  varchar(10) not null,
    label      varchar(500),
    created_at timestamptz not null default current_timestamp,
    updated_at timestamptz,
    constraint uq_about_link_tr_link_lang unique (link_id, lang_code)
);
create index if not exists ix_about_link_tr_link on about_link_tr (link_id, lang_code);


-- =====================================================================
-- STEP 2 — SEED: the Vision, Mission & Goal page
--
-- Structure only. The copy itself is typed in from the dashboard, and
-- the page stays unpublished until an editor publishes it.
-- =====================================================================
insert into about_pages (page_key, slug_az, slug_en, display_order, is_active)
values ('vision-mission-goal',
        'haqqimizda/vizyon-ve-missiya/vizyon-missiya-meqsed',
        'about/vision-mission/vision-mission-goal',
        1, false)
on conflict (page_key) do nothing;

insert into about_page_tr (page_id, lang_code, title, links_title)
select p.id, 'az', 'Vizyon, Missiya və Məqsəd', 'Bölmədə daha çox'
from about_pages p where p.page_key = 'vision-mission-goal'
on conflict (page_id, lang_code) do nothing;

insert into about_page_tr (page_id, lang_code, title, links_title)
select p.id, 'en', 'Vision, Mission & Goal', 'More in this section'
from about_pages p where p.page_key = 'vision-mission-goal'
on conflict (page_id, lang_code) do nothing;

-- The three statement cards, in the order the page renders them.
insert into about_blocks (page_id, block_key, display_order)
select p.id, v.k, v.o
from about_pages p
cross join (values ('mission', 1), ('vision', 2), ('goal', 3)) as v(k, o)
where p.page_key = 'vision-mission-goal'
on conflict (page_id, block_key) do nothing;

insert into about_block_tr (block_id, lang_code, title)
select b.id, v.lang, v.title
from about_blocks b
join about_pages p on p.id = b.page_id
join (values ('mission', 'az', 'Missiya'), ('mission', 'en', 'Mission'),
             ('vision',  'az', 'Vizyon'),  ('vision',  'en', 'Vision'),
             ('goal',    'az', 'Məqsəd'),  ('goal',    'en', 'Goal')
     ) as v(k, lang, title) on v.k = b.block_key
where p.page_key = 'vision-mission-goal'
on conflict (block_id, lang_code) do nothing;


-- =====================================================================
-- STEP 3 — VERIFY. Expect 1 page, 2 translations, 3 blocks, 6 block rows.
-- =====================================================================
select (select count(*) from about_pages)    as pages,
       (select count(*) from about_page_tr)  as page_tr,
       (select count(*) from about_blocks)   as blocks,
       (select count(*) from about_block_tr) as block_tr,
       (select count(*) from about_links)    as links;
