-- =====================================================================
-- MIGRATION — Research: "Əqli Mülkiyyət və Patentlər"
--                       (Intellectual Property and Patents)
--
-- Slugs on the website:
--   az  /az/tedqiqat/tedqiqat-fealiyyeti/eqli-mulkiyyet-ve-patentler
--   en  /en/research/research-activity/intellectual-property-and-patents
--
-- Adds:
--   research_page_tr.body_html   → renamed from vision_html (see below)
--   research_patent_years        → one year heading, one table under it
--   research_patents             → a row of that table
--   research_patent_tr           → that row's name and authors, per language
--   the `intellectual-property` page itself
--
-- Why vision_html becomes body_html: the priorities page uses it for the
-- "Strateji baxış" card and this page uses it for the paragraph above the
-- tables. Structurally they are the same thing — the page's one
-- editor-authored body — and whatever heading sits over it is drawn by the
-- website. One column named for the role beats two named for two pages.
-- The rename preserves data and is guarded, so it is safe on a database
-- that has already run migrations_research_priorities.sql and safe to
-- re-run afterwards.
--
-- Why years are their own rows rather than a column on the patent: the
-- page renders a heading per year with its own table, an editor works a
-- year at a time, and a year that has been added but not yet filled is a
-- legitimate state. Ordering is not stored as a preference — the API
-- sorts by the year itself (see below).
--
-- Why the row number ("№") has no column: it is the row's position. The
-- API derives it, so it can never disagree with the order the editor
-- arranged, and there is nothing to renumber after an insert.
--
-- Why ordering is ascending: the website reverses the list before it
-- renders, so oldest-first here is what puts the newest year on top of
-- the page. Adding a new year needs no reordering at all.
--
-- What is deliberately NOT here: the hero video, the breadcrumb, the
-- eyebrow, the table headers, the document-viewer modal and the "Digər
-- Maraqlı Bölmələr" cards. The website hard-codes them.
--
-- Run AFTER migrations_research_priorities.sql. Idempotent and additive.
-- =====================================================================


-- =====================================================================
-- STEP 1 — SCHEMA
-- =====================================================================

-- vision_html -> body_html. Renames only when the old name is still there
-- and the new one is not, so this is a no-op on an already-migrated
-- database and on one built from a later schema dump.
do $$
begin
    if exists (
        select 1 from information_schema.columns
        where table_name = 'research_page_tr' and column_name = 'vision_html'
    ) and not exists (
        select 1 from information_schema.columns
        where table_name = 'research_page_tr' and column_name = 'body_html'
    ) then
        alter table research_page_tr rename column vision_html to body_html;
    end if;
end $$;

-- Belt and braces: a database that somehow has neither column still ends
-- up with the one the application reads.
alter table research_page_tr
    add column if not exists body_html text;

create table if not exists research_patent_years (
    id            integer generated by default as identity primary key,
    page_id       integer not null references research_pages(id) on delete cascade,
    -- Shown verbatim and language-neutral: "2024", "2025".
    year          varchar(50),
    -- The order the dashboard sent them in; only ever breaks ties between
    -- equal years. The API orders by the year itself, ascending.
    display_order integer not null default 0,
    created_at    timestamptz not null default current_timestamp,
    updated_at    timestamptz
);
create index if not exists ix_research_patent_years_page
    on research_patent_years (page_id, display_order);

create table if not exists research_patents (
    id            integer generated by default as identity primary key,
    year_id       integer not null references research_patent_years(id) on delete cascade,
    -- Registration number, shown verbatim in every language:
    -- "İ 2024 0058", "№047247", "WO2023242086".
    patent_number varchar(255),
    -- The certificate: an uploaded file's path or a pasted URL (most are
    -- Google Drive links today). One column, because the page treats them
    -- alike.
    document_url  varchar(2048),
    -- The row's position, which is also its "№" on the page.
    display_order integer not null default 0,
    created_at    timestamptz not null default current_timestamp,
    updated_at    timestamptz
);
create index if not exists ix_research_patents_year
    on research_patents (year_id, display_order);

create table if not exists research_patent_tr (
    id         integer generated by default as identity primary key,
    patent_id  integer not null references research_patents(id) on delete cascade,
    lang_code  varchar(10) not null,
    -- text, not varchar: some patent titles run long, and truncating one
    -- silently would be worse than storing it.
    name       text,
    -- One line, as the table renders it: "Rəsulov Nəriman, Məmmədov Ərəstun".
    -- Not a child table — the page never addresses an author on their own,
    -- and these are free-text credits rather than links to employee records.
    authors    text,
    created_at timestamptz not null default current_timestamp,
    updated_at timestamptz,
    constraint uq_research_patent_tr_patent_lang unique (patent_id, lang_code)
);
create index if not exists ix_research_patent_tr_patent
    on research_patent_tr (patent_id, lang_code);


-- =====================================================================
-- STEP 2 — SEED: the Intellectual Property and Patents page
--
-- Structure and headings only; the copy and the patent tables are
-- entered from the dashboard, and the page stays unpublished until an
-- editor publishes it.
-- =====================================================================
insert into research_pages (page_key, template, slug_az, slug_en, display_order, is_active)
values ('intellectual-property', 'patents',
        'tedqiqat/tedqiqat-fealiyyeti/eqli-mulkiyyet-ve-patentler',
        'research/research-activity/intellectual-property-and-patents',
        2, false)
on conflict (page_key) do nothing;

insert into research_page_tr (page_id, lang_code, title, links_title)
select p.id, 'az', 'Əqli Mülkiyyət və Patentlər', 'Bölmədə daha çox'
from research_pages p where p.page_key = 'intellectual-property'
on conflict (page_id, lang_code) do nothing;

insert into research_page_tr (page_id, lang_code, title, links_title)
select p.id, 'en', 'Intellectual Property and Patents', 'More in this section'
from research_pages p where p.page_key = 'intellectual-property'
on conflict (page_id, lang_code) do nothing;


-- =====================================================================
-- STEP 3 — VERIFY. Expect two research pages — research-priorities
-- ('priorities') and intellectual-property ('patents') — the latter with
-- two translation rows and, until an editor saves, no years.
-- =====================================================================
select p.page_key, p.template, p.is_active,
       (select count(*) from research_page_tr      t where t.page_id = p.id) as translations,
       (select count(*) from research_patent_years y where y.page_id = p.id) as patent_years,
       (select count(*) from research_patents      r
          join research_patent_years y2 on y2.id = r.year_id
         where y2.page_id = p.id) as patents
from research_pages p
order by p.display_order;
