-- =====================================================================
-- MIGRATION — Hero: "Ana Səhifə Sertifikatları" (Hero Certificates)
--
-- The homepage hero keeps its single static video (the existing `hero`
-- module, untouched) and gains up to 20 QS ranking certificates shown
-- after it.
--
-- Adds:
--   hero_certificate / _tr  → one row per certificate. `certificate_id`
--       is a stable 6-digit business key — the module's public id, as in
--       `hero.hero_id` / `news.news_id` — and the translation sibling is
--       joined on it, not on the surrogate `id`. No foreign key, matching
--       the older core modules (`news_translation`) whose ORM models
--       declare neither a relationship nor a `ForeignKey`.
--       `rank_label` ("=30", "801-850") is free text and is NOT translated.
--       `family` is 'world' | 'europe' | 'subject' | 'other'.
--       `issued_date` is a bare date; the website formats it per locale.
--
-- Why no check constraint on "at least one of image / document /
-- external_url": the rule is enforced by the API (422) so an editor can
-- never be locked out of an existing row by a constraint that predates it.
--
-- Run AFTER migrations_about_regulatory_documents.sql. Idempotent and additive.
-- =====================================================================


-- =====================================================================
-- STEP 1 — SCHEMA
-- =====================================================================
create table if not exists hero_certificate (
    id             integer generated by default as identity primary key,
    -- Stable 6-digit public key the API and the _tr sibling reference.
    certificate_id integer not null unique,
    -- The rank exactly as printed on the certificate ("=30", "801-850").
    rank_label     text not null,
    -- 'world' | 'europe' | 'subject' | 'other'.
    family         varchar(32) not null,
    -- The display image the hero renders inline (image mimes only).
    image          text,
    -- The official certificate file (pdf/doc mimes).
    document       text,
    -- A certificate hosted elsewhere.
    external_url   text,
    issued_date    date,
    display_order  integer not null default 0,
    is_active      boolean not null default true,
    created_at     timestamptz not null default current_timestamp,
    updated_at     timestamptz
);
create index if not exists ix_hero_certificate_order
    on hero_certificate (is_active, display_order);

create table if not exists hero_certificate_tr (
    id             integer generated by default as identity primary key,
    -- Joins hero_certificate.certificate_id (business key, not the surrogate id).
    certificate_id integer not null,
    lang_code      varchar(2) not null,
    -- "QS Avropa 2026: Qərbi Asiya".
    title          text not null,
    -- "AVROPA 2026 — QƏRBİ ASİYA".
    kicker         varchar(255),
    -- "Ben Sowter — Baş vitse-prezident".
    signer         varchar(255),
    created_at     timestamptz not null default current_timestamp,
    updated_at     timestamptz,
    constraint uq_hero_certificate_tr_cert_lang unique (certificate_id, lang_code)
);
create index if not exists ix_hero_certificate_tr_cert
    on hero_certificate_tr (certificate_id, lang_code);


-- =====================================================================
-- STEP 2 — VERIFY. Expect both tables present and 0 certificates; the
-- certificates themselves are entered from the dashboard. The
-- "hero_certificates" permission domain is code-defined and upserted by
-- rbac_bootstrap.sync_rbac() at boot, so there is nothing to seed here.
-- =====================================================================
select c.certificate_id,
       c.rank_label,
       c.family,
       c.display_order,
       c.is_active,
       (select count(*) from hero_certificate_tr t
         where t.certificate_id = c.certificate_id) as translations
from hero_certificate c
order by c.display_order;
