-- Adds GENERATED BY DEFAULT AS IDENTITY to every `id` column in the public
-- schema that is an integer/bigint primary key and isn't already an identity.
-- Also resyncs the implicit identity sequence to max(id)+1 so future inserts
-- don't collide with rows that were inserted with explicit ids.

do $$
declare
    r record;
    max_id bigint;
    seq_name text;
begin
    for r in
        select c.table_schema,
               c.table_name,
               c.column_name,
               c.data_type
        from information_schema.columns c
        join information_schema.table_constraints tc
          on tc.table_schema = c.table_schema
         and tc.table_name = c.table_name
         and tc.constraint_type = 'PRIMARY KEY'
        join information_schema.key_column_usage kcu
          on kcu.constraint_name = tc.constraint_name
         and kcu.table_schema = tc.table_schema
         and kcu.column_name = c.column_name
        where c.table_schema = 'public'
          and c.column_name = 'id'
          and c.data_type in ('integer', 'bigint')
          and c.is_identity = 'NO'
    loop
        execute format(
            'alter table %I.%I alter column %I drop default',
            r.table_schema, r.table_name, r.column_name
        );

        execute format(
            'alter table %I.%I alter column %I add generated by default as identity',
            r.table_schema, r.table_name, r.column_name
        );

        execute format('select coalesce(max(%I), 0) from %I.%I',
                       r.column_name, r.table_schema, r.table_name)
        into max_id;

        seq_name := pg_get_serial_sequence(
            format('%I.%I', r.table_schema, r.table_name),
            r.column_name
        );

        if seq_name is not null and max_id > 0 then
            execute format('select setval(%L, %s, true)', seq_name, max_id);
        end if;
    end loop;
end $$;
