-- =====================================================================
-- MIGRATION — About: "AzTU-nun Tarixi" (History of AzTU)
--
-- Adds:
--   about_pages.template   → which editor/renderer a page uses
--   about_milestones       → one row per year on the timeline
--   about_milestone_tr     → that year's heading and text, per language
--   the `history` page itself
--
-- Why a `template` column: the About pages are not all the same shape.
-- "Vizyon, Missiya və Məqsəd" is three statement cards plus a button
-- block; "AzTU-nun Tarixi" is a timeline and nothing else. The column
-- lets the dashboard show the right form — and later lets the website
-- pick the right renderer — instead of guessing from what data happens
-- to exist.
--
-- Why `year` is text and not an integer: the timeline ends on a
-- non-numeric entry ("Bu gün" / "Today"), and some entries read like
-- "1887-1905". Sorting is handled in the API, not by this column.
--
-- Run AFTER migrations_about.sql. Idempotent and additive.
-- =====================================================================


-- =====================================================================
-- STEP 1 — SCHEMA
-- =====================================================================
alter table about_pages
    add column if not exists template varchar(50) not null default 'statements';

-- The page that already exists predates the column, so name its shape
-- explicitly rather than leaning on the default.
update about_pages set template = 'statements' where page_key = 'vision-mission-goal';

create table if not exists about_milestones (
    id            integer generated by default as identity primary key,
    page_id       integer not null references about_pages(id) on delete cascade,
    -- Display value, shown verbatim: "1950", "1887-1905", "Bu gün".
    year          varchar(50),
    -- Tie-break only; the API orders by the year itself (newest first).
    display_order integer not null default 0,
    created_at    timestamptz not null default current_timestamp,
    updated_at    timestamptz
);
create index if not exists ix_about_milestones_page
    on about_milestones (page_id, display_order);

create table if not exists about_milestone_tr (
    id           integer generated by default as identity primary key,
    milestone_id integer not null references about_milestones(id) on delete cascade,
    lang_code    varchar(10) not null,
    title        varchar(500),
    description  text,
    created_at   timestamptz not null default current_timestamp,
    updated_at   timestamptz,
    constraint uq_about_milestone_tr_ms_lang unique (milestone_id, lang_code)
);
create index if not exists ix_about_milestone_tr_ms
    on about_milestone_tr (milestone_id, lang_code);


-- =====================================================================
-- STEP 2 — SEED: the History page
--
-- Structure only; the milestones themselves are entered from the
-- dashboard. The page stays unpublished until an editor publishes it.
-- =====================================================================
insert into about_pages (page_key, template, slug_az, slug_en, display_order, is_active)
values ('history', 'timeline',
        'haqqimizda/vizyon-ve-missiya/aztu-nun-tarixi',
        'about/vision-mission/history-of-aztu',
        2, false)
on conflict (page_key) do nothing;

insert into about_page_tr (page_id, lang_code, title, links_title)
select p.id, 'az', 'AzTU-nun Tarixi', 'Bölmədə daha çox'
from about_pages p where p.page_key = 'history'
on conflict (page_id, lang_code) do nothing;

insert into about_page_tr (page_id, lang_code, title, links_title)
select p.id, 'en', 'History of AzTU', 'More in this section'
from about_pages p where p.page_key = 'history'
on conflict (page_id, lang_code) do nothing;


-- =====================================================================
-- STEP 3 — VERIFY. Expect 2 pages, and history with template 'timeline'.
-- =====================================================================
select page_key, template, is_active, slug_az
from about_pages
order by display_order;
