-- =====================================================================
-- MIGRATION — About: "Prorektorlar" (Vice-Rectors)
--
-- Adds:
--   about_page_tr.domains        → the comma-separated category line the
--       hero renders ("Academic · Science · International · Finance"),
--       stored per language exactly as the editor types it
--   about_page_tr.section_title  → the page's second heading
--       ("Executive Leadership"), per language
--   about_page_tr.section_body   → the rich-text paragraph under it
--   about_persons / _tr          → the vice-rector cards, each with its
--       own detail ("see profile") copy
--   the `vice-rector` page itself
--
-- Why a new `about_persons` table rather than reusing `about_lists` or
-- `about_images`: a vice-rector is a structured record — a name, a
-- degree, a title, contact details and a long biography, half of it
-- bilingual — not a flat string or a photo. It is the same shape the
-- rector page would want if it ever listed more than one person, so the
-- table is named generically (`about_persons`) rather than for this page.
--
-- Why email/phone/phone_code sit on the person row and not the
-- translation: an address and a number read the same in both languages.
-- `phone_code` (an internal extension) is the one optional field; every
-- other field is required by the dashboard when a person is created.
--
-- Run AFTER migrations_about_rector.sql. Idempotent and additive.
-- =====================================================================


-- =====================================================================
-- STEP 1 — SCHEMA
-- =====================================================================
alter table about_page_tr add column if not exists domains       text;
alter table about_page_tr add column if not exists section_title varchar(500);
alter table about_page_tr add column if not exists section_body  text;

create table if not exists about_persons (
    id            integer generated by default as identity primary key,
    page_id       integer not null references about_pages(id) on delete cascade,
    email         varchar(255),
    phone         varchar(100),
    -- Optional internal extension, e.g. "1204".
    phone_code    varchar(50),
    display_order integer not null default 0,
    created_at    timestamptz not null default current_timestamp,
    updated_at    timestamptz
);
create index if not exists ix_about_persons_page
    on about_persons (page_id, display_order);

create table if not exists about_person_tr (
    id         integer generated by default as identity primary key,
    person_id  integer not null references about_persons(id) on delete cascade,
    lang_code  varchar(10) not null,
    -- "Prof. Subhan Namazov" — the name with its scientific title prefix.
    name       varchar(500),
    -- "Doctor of Technical Sciences, Professor".
    degree     varchar(500),
    -- "Vice-Rector for Academic Affairs".
    position   varchar(500),
    -- The long profile shown behind the card's "see profile" button.
    bio        text,
    created_at timestamptz not null default current_timestamp,
    updated_at timestamptz,
    constraint uq_about_person_tr_person_lang unique (person_id, lang_code)
);
create index if not exists ix_about_person_tr_person
    on about_person_tr (person_id, lang_code);


-- =====================================================================
-- STEP 2 — SEED: the Vice-Rectors page
--
-- Structure and known chrome only; the vice-rectors themselves are
-- entered from the dashboard. The page stays unpublished until an editor
-- publishes it.
-- =====================================================================
insert into about_pages (page_key, template, slug_az, slug_en, display_order, is_active)
values ('vice-rector', 'vice-rector',
        'haqqimizda/rehbetlik-ve-idareetme/prorektorlar',
        'about/leadership-and-management/vice-rectors',
        5, false)
on conflict (page_key) do nothing;

insert into about_page_tr (page_id, lang_code, title, domains, section_title, links_title)
select p.id, 'az', 'Prorektorlar',
       'Akademik · Elm · Beynəlxalq · Maliyyə',
       'İcraçı Rəhbərlik',
       'Bölmədə daha çox'
from about_pages p where p.page_key = 'vice-rector'
on conflict (page_id, lang_code) do nothing;

insert into about_page_tr (page_id, lang_code, title, domains, section_title, links_title)
select p.id, 'en', 'Vice-Rectors',
       'Academic · Science · International · Finance',
       'Executive Leadership',
       'More in this section'
from about_pages p where p.page_key = 'vice-rector'
on conflict (page_id, lang_code) do nothing;


-- =====================================================================
-- STEP 3 — VERIFY. Expect the vice-rector page with 0 persons to start.
-- =====================================================================
select p.page_key, p.template, p.is_active,
       (select count(*) from about_persons x where x.page_id = p.id) as persons
from about_pages p
where p.page_key = 'vice-rector';
