-- =====================================================================
-- MIGRATION — About: "Elmi Şura" (Scientific Board)
--
-- Adds:
--   about_page_tr.councils_title  → the heading above the councils list,
--       per language ("Şuralar" / "Councils")
--   about_councils / _tr          → an unlimited, ordered list of councils
--       on the page, each with a bilingual name
--   about_council_members / _tr   → the people on a council. One table holds
--       both rosters — the council's members and its secretariat — told apart
--       by `role` ('member' | 'secretary'). Name, surname and duty (position)
--       are bilingual and live on the `*_tr` sibling.
--   the `scientific-board` page itself
--
-- Why one members table with a `role` column rather than two tables: a
-- secretariat member has the exact same shape as an ordinary member
-- (name, surname, duty, all bilingual). A discriminator keeps the schema
-- and the writer half the size, and the dashboard still edits the two
-- rosters as separate lists.
--
-- The page's other copy reuses columns the About model already has:
--   title          → the page title
--   description    → the short description (rich text)
--   section_title  → the second title
--   section_body   → the second description (rich text)
--   links_title + about_links → the "More in this section" buttons
--
-- Run AFTER migrations_about_vice_rector.sql. Idempotent and additive.
-- =====================================================================


-- =====================================================================
-- STEP 1 — SCHEMA
-- =====================================================================
alter table about_page_tr add column if not exists councils_title varchar(500);

create table if not exists about_councils (
    id            integer generated by default as identity primary key,
    page_id       integer not null references about_pages(id) on delete cascade,
    display_order integer not null default 0,
    created_at    timestamptz not null default current_timestamp,
    updated_at    timestamptz
);
create index if not exists ix_about_councils_page
    on about_councils (page_id, display_order);

create table if not exists about_council_tr (
    id         integer generated by default as identity primary key,
    council_id integer not null references about_councils(id) on delete cascade,
    lang_code  varchar(10) not null,
    -- "Böyük Elmi Şura" / "Grand Scientific Council".
    name       varchar(500),
    created_at timestamptz not null default current_timestamp,
    updated_at timestamptz,
    constraint uq_about_council_tr_council_lang unique (council_id, lang_code)
);
create index if not exists ix_about_council_tr_council
    on about_council_tr (council_id, lang_code);

create table if not exists about_council_members (
    id            integer generated by default as identity primary key,
    council_id    integer not null references about_councils(id) on delete cascade,
    -- Which roster this row belongs to: 'member' | 'secretary'.
    role          varchar(20) not null default 'member',
    display_order integer not null default 0,
    created_at    timestamptz not null default current_timestamp,
    updated_at    timestamptz
);
create index if not exists ix_about_council_members_council
    on about_council_members (council_id, role, display_order);

create table if not exists about_council_member_tr (
    id         integer generated by default as identity primary key,
    member_id  integer not null references about_council_members(id) on delete cascade,
    lang_code  varchar(10) not null,
    name       varchar(255),
    surname    varchar(255),
    -- The person's duty on the council.
    position   varchar(500),
    created_at timestamptz not null default current_timestamp,
    updated_at timestamptz,
    constraint uq_about_council_member_tr_member_lang unique (member_id, lang_code)
);
create index if not exists ix_about_council_member_tr_member
    on about_council_member_tr (member_id, lang_code);


-- =====================================================================
-- STEP 2 — SEED: the Scientific Board page
--
-- Structure and known chrome only; the councils and their people are
-- entered from the dashboard. The page stays unpublished until an editor
-- publishes it.
-- =====================================================================
insert into about_pages (page_key, template, slug_az, slug_en, display_order, is_active, created_at)
values ('scientific-board', 'scientific-board',
        'haqqimizda/rehbetlik-ve-idareetme/elmi-sura',
        'about/leadership-and-management/scientific-board',
        6, false, current_timestamp)
on conflict (page_key) do nothing;

insert into about_page_tr (page_id, lang_code, title, councils_title, links_title, created_at)
select p.id, 'az', 'Elmi Şura', 'Şuralar', 'Bölmədə daha çox', current_timestamp
from about_pages p where p.page_key = 'scientific-board'
on conflict (page_id, lang_code) do nothing;

insert into about_page_tr (page_id, lang_code, title, councils_title, links_title, created_at)
select p.id, 'en', 'Scientific Board', 'Councils', 'More in this section', current_timestamp
from about_pages p where p.page_key = 'scientific-board'
on conflict (page_id, lang_code) do nothing;


-- =====================================================================
-- STEP 3 — VERIFY. Expect the scientific-board page with 0 councils.
-- =====================================================================
select p.page_key, p.template, p.is_active,
       (select count(*) from about_councils c where c.page_id = p.id) as councils
from about_pages p
where p.page_key = 'scientific-board';
