-- =====================================================================
-- SEED — About page registry and section skeleton
--
-- Generated by `python -m app.scripts.seed_about_pages --sql`.
-- Do not edit by hand; change BLUEPRINT in that script and regenerate.
--
-- Run AFTER migrations_about_pages.sql, in one psql session. Every
-- statement is idempotent: existing pages and sections are left exactly
-- as an editor left them, so this is safe to re-run after new pages are
-- added to the blueprint.
--
-- Pages land with is_active = false — nothing is public until it is
-- explicitly published from the dashboard.
-- =====================================================================

-- ── history ─────────────────────────────────────────────────────
insert into about_pages (page_key, group_key, template, slug_az, slug_en, display_order, is_active)
values ('history', 'vision_mission', 'history', 'vizyon-ve-missiya/aztu-nun-tarixi', 'vision-mission/history-of-aztu', 1, false)
on conflict (page_key) do nothing;
insert into about_page_tr (page_id, lang_code, eyebrow, title, breadcrumb)
select p.id, 'az', 'Mirasımız', 'AzTU-nun Tarixi', 'Tarix'
from about_pages p where p.page_key = 'history'
on conflict (page_id, lang_code) do nothing;
insert into about_page_tr (page_id, lang_code, eyebrow, title, breadcrumb)
select p.id, 'en', 'Our Legacy', 'History of AzTU', 'History'
from about_pages p where p.page_key = 'history'
on conflict (page_id, lang_code) do nothing;
insert into about_sections (page_id, section_key, section_type, display_order, is_active)
select p.id, 'milestones', 'timeline', 1, true
from about_pages p where p.page_key = 'history'
on conflict (page_id, section_key) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'az', 'Əsas Mərhələlər'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'history' and s.section_key = 'milestones'
on conflict (section_id, lang_code) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'en', 'Key Milestones'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'history' and s.section_key = 'milestones'
on conflict (section_id, lang_code) do nothing;
insert into about_sections (page_id, section_key, section_type, display_order, is_active)
select p.id, 'stats', 'stats', 2, true
from about_pages p where p.page_key = 'history'
on conflict (page_id, section_key) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'az', 'Rəqəmlərlə AzTU'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'history' and s.section_key = 'stats'
on conflict (section_id, lang_code) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'en', 'AzTU in Numbers'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'history' and s.section_key = 'stats'
on conflict (section_id, lang_code) do nothing;
insert into about_sections (page_id, section_key, section_type, display_order, is_active)
select p.id, 'related', 'links', 3, true
from about_pages p where p.page_key = 'history'
on conflict (page_id, section_key) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'az', 'Bölmədə daha çox'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'history' and s.section_key = 'related'
on conflict (section_id, lang_code) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'en', 'More in this section'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'history' and s.section_key = 'related'
on conflict (section_id, lang_code) do nothing;

-- ── vision ──────────────────────────────────────────────────────
insert into about_pages (page_key, group_key, template, slug_az, slug_en, display_order, is_active)
values ('vision', 'vision_mission', 'statement', 'vizyon-ve-missiya/vizyon', 'vision-mission/vision', 2, false)
on conflict (page_key) do nothing;
insert into about_page_tr (page_id, lang_code, eyebrow, title, breadcrumb)
select p.id, 'az', 'İstiqamətimiz', 'Vizyon', 'Vizyon'
from about_pages p where p.page_key = 'vision'
on conflict (page_id, lang_code) do nothing;
insert into about_page_tr (page_id, lang_code, eyebrow, title, breadcrumb)
select p.id, 'en', 'Our Direction', 'Vision', 'Vision'
from about_pages p where p.page_key = 'vision'
on conflict (page_id, lang_code) do nothing;
insert into about_sections (page_id, section_key, section_type, display_order, is_active)
select p.id, 'statement', 'quote', 1, true
from about_pages p where p.page_key = 'vision'
on conflict (page_id, section_key) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'az', 'Vizyon Bəyanatımız'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'vision' and s.section_key = 'statement'
on conflict (section_id, lang_code) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'en', 'Our Vision Statement'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'vision' and s.section_key = 'statement'
on conflict (section_id, lang_code) do nothing;
insert into about_sections (page_id, section_key, section_type, display_order, is_active)
select p.id, 'related', 'links', 2, true
from about_pages p where p.page_key = 'vision'
on conflict (page_id, section_key) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'az', 'Bölmədə daha çox'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'vision' and s.section_key = 'related'
on conflict (section_id, lang_code) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'en', 'More in this section'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'vision' and s.section_key = 'related'
on conflict (section_id, lang_code) do nothing;

-- ── mission ─────────────────────────────────────────────────────
insert into about_pages (page_key, group_key, template, slug_az, slug_en, display_order, is_active)
values ('mission', 'vision_mission', 'statement', 'vizyon-ve-missiya/missiya', 'vision-mission/mission', 3, false)
on conflict (page_key) do nothing;
insert into about_page_tr (page_id, lang_code, eyebrow, title, breadcrumb)
select p.id, 'az', 'Məqsədimiz', 'Missiya', 'Missiya'
from about_pages p where p.page_key = 'mission'
on conflict (page_id, lang_code) do nothing;
insert into about_page_tr (page_id, lang_code, eyebrow, title, breadcrumb)
select p.id, 'en', 'Our Purpose', 'Mission', 'Mission'
from about_pages p where p.page_key = 'mission'
on conflict (page_id, lang_code) do nothing;
insert into about_sections (page_id, section_key, section_type, display_order, is_active)
select p.id, 'statement', 'quote', 1, true
from about_pages p where p.page_key = 'mission'
on conflict (page_id, section_key) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'az', 'Missiya Bəyanatımız'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'mission' and s.section_key = 'statement'
on conflict (section_id, lang_code) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'en', 'Our Mission Statement'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'mission' and s.section_key = 'statement'
on conflict (section_id, lang_code) do nothing;
insert into about_sections (page_id, section_key, section_type, display_order, is_active)
select p.id, 'related', 'links', 2, true
from about_pages p where p.page_key = 'mission'
on conflict (page_id, section_key) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'az', 'Bölmədə daha çox'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'mission' and s.section_key = 'related'
on conflict (section_id, lang_code) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'en', 'More in this section'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'mission' and s.section_key = 'related'
on conflict (section_id, lang_code) do nothing;

-- ── strategic-plan ──────────────────────────────────────────────
insert into about_pages (page_key, group_key, template, slug_az, slug_en, display_order, is_active)
values ('strategic-plan', 'vision_mission', 'strategic_plan', 'vizyon-ve-missiya/strateji-plan', 'vision-mission/strategic-plan', 4, false)
on conflict (page_key) do nothing;
insert into about_page_tr (page_id, lang_code, eyebrow, title, breadcrumb)
select p.id, 'az', 'Vizyon 2030', 'Strateji İnkişaf Planı', 'Strateji Plan'
from about_pages p where p.page_key = 'strategic-plan'
on conflict (page_id, lang_code) do nothing;
insert into about_page_tr (page_id, lang_code, eyebrow, title, breadcrumb)
select p.id, 'en', 'Vision 2030', 'Strategic Development Plan', 'Strategic Plan'
from about_pages p where p.page_key = 'strategic-plan'
on conflict (page_id, lang_code) do nothing;
insert into about_sections (page_id, section_key, section_type, display_order, is_active)
select p.id, 'vision', 'paragraphs', 1, true
from about_pages p where p.page_key = 'strategic-plan'
on conflict (page_id, section_key) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'az', 'Vizyon'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'strategic-plan' and s.section_key = 'vision'
on conflict (section_id, lang_code) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'en', 'Vision'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'strategic-plan' and s.section_key = 'vision'
on conflict (section_id, lang_code) do nothing;
insert into about_sections (page_id, section_key, section_type, display_order, is_active)
select p.id, 'mission', 'paragraphs', 2, true
from about_pages p where p.page_key = 'strategic-plan'
on conflict (page_id, section_key) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'az', 'Missiya'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'strategic-plan' and s.section_key = 'mission'
on conflict (section_id, lang_code) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'en', 'Mission'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'strategic-plan' and s.section_key = 'mission'
on conflict (section_id, lang_code) do nothing;
insert into about_sections (page_id, section_key, section_type, display_order, is_active)
select p.id, 'pillars', 'pillars', 3, true
from about_pages p where p.page_key = 'strategic-plan'
on conflict (page_id, section_key) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'az', 'Strateji Sütunlar'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'strategic-plan' and s.section_key = 'pillars'
on conflict (section_id, lang_code) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'en', 'Strategic Pillars'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'strategic-plan' and s.section_key = 'pillars'
on conflict (section_id, lang_code) do nothing;
insert into about_sections (page_id, section_key, section_type, display_order, is_active)
select p.id, 'values', 'list', 4, true
from about_pages p where p.page_key = 'strategic-plan'
on conflict (page_id, section_key) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'az', 'Korporativ Dəyərlər'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'strategic-plan' and s.section_key = 'values'
on conflict (section_id, lang_code) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'en', 'Corporate Values'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'strategic-plan' and s.section_key = 'values'
on conflict (section_id, lang_code) do nothing;
insert into about_sections (page_id, section_key, section_type, display_order, is_active)
select p.id, 'targets', 'list', 5, true
from about_pages p where p.page_key = 'strategic-plan'
on conflict (page_id, section_key) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'az', 'Əsas Performans Göstəriciləri (KPI)'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'strategic-plan' and s.section_key = 'targets'
on conflict (section_id, lang_code) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'en', 'Key Performance Indicators (KPI)'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'strategic-plan' and s.section_key = 'targets'
on conflict (section_id, lang_code) do nothing;
insert into about_sections (page_id, section_key, section_type, display_order, is_active)
select p.id, 'related', 'links', 6, true
from about_pages p where p.page_key = 'strategic-plan'
on conflict (page_id, section_key) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'az', 'Bölmədə daha çox'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'strategic-plan' and s.section_key = 'related'
on conflict (section_id, lang_code) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'en', 'More in this section'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'strategic-plan' and s.section_key = 'related'
on conflict (section_id, lang_code) do nothing;

-- ── anniversary-film ────────────────────────────────────────────
insert into about_pages (page_key, group_key, template, slug_az, slug_en, display_order, is_active)
values ('anniversary-film', 'vision_mission', 'video', 'vizyon-ve-missiya/75-illik-yubiley-filmi', 'vision-mission/75th-anniversary-film', 5, false)
on conflict (page_key) do nothing;
insert into about_page_tr (page_id, lang_code, eyebrow, title, breadcrumb)
select p.id, 'az', 'Tədbir', '75 İllik Yubiley Filmi', 'Yubiley Filmi'
from about_pages p where p.page_key = 'anniversary-film'
on conflict (page_id, lang_code) do nothing;
insert into about_page_tr (page_id, lang_code, eyebrow, title, breadcrumb)
select p.id, 'en', 'Event', '75th Anniversary Film', 'Anniversary Film'
from about_pages p where p.page_key = 'anniversary-film'
on conflict (page_id, lang_code) do nothing;
insert into about_sections (page_id, section_key, section_type, display_order, is_active)
select p.id, 'film', 'video', 1, true
from about_pages p where p.page_key = 'anniversary-film'
on conflict (page_id, section_key) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'az', 'Film'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'anniversary-film' and s.section_key = 'film'
on conflict (section_id, lang_code) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'en', 'Film'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'anniversary-film' and s.section_key = 'film'
on conflict (section_id, lang_code) do nothing;
insert into about_sections (page_id, section_key, section_type, display_order, is_active)
select p.id, 'related', 'links', 2, true
from about_pages p where p.page_key = 'anniversary-film'
on conflict (page_id, section_key) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'az', 'Bölmədə daha çox'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'anniversary-film' and s.section_key = 'related'
on conflict (section_id, lang_code) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'en', 'More in this section'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'anniversary-film' and s.section_key = 'related'
on conflict (section_id, lang_code) do nothing;

-- ── vision-mission-goal ─────────────────────────────────────────
insert into about_pages (page_key, group_key, template, slug_az, slug_en, display_order, is_active)
values ('vision-mission-goal', 'vision_mission', 'statement', 'vizyon-ve-missiya/vizyon-missiya-meqsed', 'vision-mission/vision-mission-goal', 6, false)
on conflict (page_key) do nothing;
insert into about_page_tr (page_id, lang_code, eyebrow, title, breadcrumb)
select p.id, 'az', 'Kimliyimiz', 'Vizyon, Missiya və Məqsəd', 'Vizyon, Missiya və Məqsəd'
from about_pages p where p.page_key = 'vision-mission-goal'
on conflict (page_id, lang_code) do nothing;
insert into about_page_tr (page_id, lang_code, eyebrow, title, breadcrumb)
select p.id, 'en', 'Our Identity', 'Vision, Mission & Goal', 'Vision, Mission & Goal'
from about_pages p where p.page_key = 'vision-mission-goal'
on conflict (page_id, lang_code) do nothing;
insert into about_sections (page_id, section_key, section_type, display_order, is_active)
select p.id, 'mission', 'paragraphs', 1, true
from about_pages p where p.page_key = 'vision-mission-goal'
on conflict (page_id, section_key) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'az', 'Missiya'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'vision-mission-goal' and s.section_key = 'mission'
on conflict (section_id, lang_code) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'en', 'Mission'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'vision-mission-goal' and s.section_key = 'mission'
on conflict (section_id, lang_code) do nothing;
insert into about_sections (page_id, section_key, section_type, display_order, is_active)
select p.id, 'vision', 'paragraphs', 2, true
from about_pages p where p.page_key = 'vision-mission-goal'
on conflict (page_id, section_key) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'az', 'Vizyon'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'vision-mission-goal' and s.section_key = 'vision'
on conflict (section_id, lang_code) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'en', 'Vision'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'vision-mission-goal' and s.section_key = 'vision'
on conflict (section_id, lang_code) do nothing;
insert into about_sections (page_id, section_key, section_type, display_order, is_active)
select p.id, 'goal', 'paragraphs', 3, true
from about_pages p where p.page_key = 'vision-mission-goal'
on conflict (page_id, section_key) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'az', 'Məqsəd'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'vision-mission-goal' and s.section_key = 'goal'
on conflict (section_id, lang_code) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'en', 'Goal'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'vision-mission-goal' and s.section_key = 'goal'
on conflict (section_id, lang_code) do nothing;
insert into about_sections (page_id, section_key, section_type, display_order, is_active)
select p.id, 'related', 'links', 4, true
from about_pages p where p.page_key = 'vision-mission-goal'
on conflict (page_id, section_key) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'az', 'Bölmədə daha çox'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'vision-mission-goal' and s.section_key = 'related'
on conflict (section_id, lang_code) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'en', 'More in this section'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'vision-mission-goal' and s.section_key = 'related'
on conflict (section_id, lang_code) do nothing;

-- ── rector ──────────────────────────────────────────────────────
insert into about_pages (page_key, group_key, template, slug_az, slug_en, display_order, is_active)
values ('rector', 'leadership', 'rector', 'rehbetlik-ve-idareetme/rektor', 'leadership-and-management/rector', 10, false)
on conflict (page_key) do nothing;
insert into about_page_tr (page_id, lang_code, eyebrow, title, breadcrumb)
select p.id, 'az', 'Rəhbərlik və İdarəetmə', 'Rektor', 'Rektor'
from about_pages p where p.page_key = 'rector'
on conflict (page_id, lang_code) do nothing;
insert into about_page_tr (page_id, lang_code, eyebrow, title, breadcrumb)
select p.id, 'en', 'Leadership & Governance', 'Rector', 'Rector'
from about_pages p where p.page_key = 'rector'
on conflict (page_id, lang_code) do nothing;
insert into about_sections (page_id, section_key, section_type, display_order, is_active)
select p.id, 'message', 'paragraphs', 1, true
from about_pages p where p.page_key = 'rector'
on conflict (page_id, section_key) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'az', 'Rektorun Müraciəti'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'rector' and s.section_key = 'message'
on conflict (section_id, lang_code) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'en', 'Message from the Rector'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'rector' and s.section_key = 'message'
on conflict (section_id, lang_code) do nothing;
insert into about_sections (page_id, section_key, section_type, display_order, is_active)
select p.id, 'priorities', 'list', 2, true
from about_pages p where p.page_key = 'rector'
on conflict (page_id, section_key) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'az', 'Əsas fəaliyyət istiqamətlərimiz'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'rector' and s.section_key = 'priorities'
on conflict (section_id, lang_code) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'en', 'Our Key Priorities'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'rector' and s.section_key = 'priorities'
on conflict (section_id, lang_code) do nothing;
insert into about_sections (page_id, section_key, section_type, display_order, is_active)
select p.id, 'message_closing', 'paragraphs', 3, true
from about_pages p where p.page_key = 'rector'
on conflict (page_id, section_key) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'az', 'Müraciətin sonu'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'rector' and s.section_key = 'message_closing'
on conflict (section_id, lang_code) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'en', 'Closing Remarks'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'rector' and s.section_key = 'message_closing'
on conflict (section_id, lang_code) do nothing;
insert into about_sections (page_id, section_key, section_type, display_order, is_active)
select p.id, 'responsibilities', 'list', 4, true
from about_pages p where p.page_key = 'rector'
on conflict (page_id, section_key) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'az', 'Vəzifə Öhdəlikləri'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'rector' and s.section_key = 'responsibilities'
on conflict (section_id, lang_code) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'en', 'Responsibilities'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'rector' and s.section_key = 'responsibilities'
on conflict (section_id, lang_code) do nothing;
insert into about_sections (page_id, section_key, section_type, display_order, is_active)
select p.id, 'about_rector', 'paragraphs', 5, true
from about_pages p where p.page_key = 'rector'
on conflict (page_id, section_key) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'az', 'Rektor haqqında'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'rector' and s.section_key = 'about_rector'
on conflict (section_id, lang_code) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'en', 'About the Rector'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'rector' and s.section_key = 'about_rector'
on conflict (section_id, lang_code) do nothing;
insert into about_sections (page_id, section_key, section_type, display_order, is_active)
select p.id, 'departments', 'list', 6, true
from about_pages p where p.page_key = 'rector'
on conflict (page_id, section_key) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'az', 'Rektora tabe olan strukturlar'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'rector' and s.section_key = 'departments'
on conflict (section_id, lang_code) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'en', 'Units Reporting to the Rector'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'rector' and s.section_key = 'departments'
on conflict (section_id, lang_code) do nothing;
insert into about_sections (page_id, section_key, section_type, display_order, is_active)
select p.id, 'gallery', 'gallery', 7, true
from about_pages p where p.page_key = 'rector'
on conflict (page_id, section_key) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'az', 'Rektorun Qalereyası'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'rector' and s.section_key = 'gallery'
on conflict (section_id, lang_code) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'en', 'Rector''s Gallery'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'rector' and s.section_key = 'gallery'
on conflict (section_id, lang_code) do nothing;
insert into about_sections (page_id, section_key, section_type, display_order, is_active)
select p.id, 'related', 'links', 8, true
from about_pages p where p.page_key = 'rector'
on conflict (page_id, section_key) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'az', 'Bölmədə daha çox'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'rector' and s.section_key = 'related'
on conflict (section_id, lang_code) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'en', 'More in this section'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'rector' and s.section_key = 'related'
on conflict (section_id, lang_code) do nothing;

-- ── vice-rector ─────────────────────────────────────────────────
insert into about_pages (page_key, group_key, template, slug_az, slug_en, display_order, is_active)
values ('vice-rector', 'leadership', 'people', 'vice-rector', 'vice-rector', 11, false)
on conflict (page_key) do nothing;
insert into about_page_tr (page_id, lang_code, eyebrow, title, breadcrumb)
select p.id, 'az', 'Rəhbərlik və İdarəetmə', 'Prorektorlar', 'Prorektorlar'
from about_pages p where p.page_key = 'vice-rector'
on conflict (page_id, lang_code) do nothing;
insert into about_page_tr (page_id, lang_code, eyebrow, title, breadcrumb)
select p.id, 'en', 'Leadership & Governance', 'Vice-Rectors', 'Vice-Rectors'
from about_pages p where p.page_key = 'vice-rector'
on conflict (page_id, lang_code) do nothing;
insert into about_sections (page_id, section_key, section_type, display_order, is_active)
select p.id, 'overview', 'paragraphs', 1, true
from about_pages p where p.page_key = 'vice-rector'
on conflict (page_id, section_key) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'az', 'Ümumi məlumat'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'vice-rector' and s.section_key = 'overview'
on conflict (section_id, lang_code) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'en', 'Overview'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'vice-rector' and s.section_key = 'overview'
on conflict (section_id, lang_code) do nothing;
insert into about_sections (page_id, section_key, section_type, display_order, is_active)
select p.id, 'vice_rectors', 'people', 2, true
from about_pages p where p.page_key = 'vice-rector'
on conflict (page_id, section_key) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'az', 'Prorektorlar'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'vice-rector' and s.section_key = 'vice_rectors'
on conflict (section_id, lang_code) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'en', 'Vice-Rectors'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'vice-rector' and s.section_key = 'vice_rectors'
on conflict (section_id, lang_code) do nothing;
insert into about_sections (page_id, section_key, section_type, display_order, is_active)
select p.id, 'labels', 'list', 3, true
from about_pages p where p.page_key = 'vice-rector'
on conflict (page_id, section_key) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'az', 'İnterfeys mətnləri'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'vice-rector' and s.section_key = 'labels'
on conflict (section_id, lang_code) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'en', 'Interface labels'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'vice-rector' and s.section_key = 'labels'
on conflict (section_id, lang_code) do nothing;
insert into about_sections (page_id, section_key, section_type, display_order, is_active)
select p.id, 'related', 'links', 4, true
from about_pages p where p.page_key = 'vice-rector'
on conflict (page_id, section_key) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'az', 'Bölmədə daha çox'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'vice-rector' and s.section_key = 'related'
on conflict (section_id, lang_code) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'en', 'More in this section'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'vice-rector' and s.section_key = 'related'
on conflict (section_id, lang_code) do nothing;

-- ── rectors-office ──────────────────────────────────────────────
insert into about_pages (page_key, group_key, template, slug_az, slug_en, display_order, is_active)
values ('rectors-office', 'leadership', 'people', 'rectors-office', 'rectors-office', 12, false)
on conflict (page_key) do nothing;
insert into about_page_tr (page_id, lang_code, eyebrow, title, breadcrumb)
select p.id, 'az', 'Rəhbərlik və İdarəetmə', 'Rektorat', 'Rektorat'
from about_pages p where p.page_key = 'rectors-office'
on conflict (page_id, lang_code) do nothing;
insert into about_page_tr (page_id, lang_code, eyebrow, title, breadcrumb)
select p.id, 'en', 'Leadership & Governance', 'Rector''s Office', 'Rectorate'
from about_pages p where p.page_key = 'rectors-office'
on conflict (page_id, lang_code) do nothing;
insert into about_sections (page_id, section_key, section_type, display_order, is_active)
select p.id, 'staff', 'people', 1, true
from about_pages p where p.page_key = 'rectors-office'
on conflict (page_id, section_key) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'az', 'Rektorat heyəti'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'rectors-office' and s.section_key = 'staff'
on conflict (section_id, lang_code) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'en', 'Rectorate Staff'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'rectors-office' and s.section_key = 'staff'
on conflict (section_id, lang_code) do nothing;

-- ── scientific-board ────────────────────────────────────────────
insert into about_pages (page_key, group_key, template, slug_az, slug_en, display_order, is_active)
values ('scientific-board', 'leadership', 'board', 'scientific-board', 'scientific-board', 13, false)
on conflict (page_key) do nothing;
insert into about_page_tr (page_id, lang_code, eyebrow, title, breadcrumb)
select p.id, 'az', 'Rəhbərlik və İdarəetmə', 'Elmi Şura', 'Elmi Şura'
from about_pages p where p.page_key = 'scientific-board'
on conflict (page_id, lang_code) do nothing;
insert into about_page_tr (page_id, lang_code, eyebrow, title, breadcrumb)
select p.id, 'en', 'Leadership & Governance', 'Scientific Board', 'Scientific Board'
from about_pages p where p.page_key = 'scientific-board'
on conflict (page_id, lang_code) do nothing;
insert into about_sections (page_id, section_key, section_type, display_order, is_active)
select p.id, 'about', 'paragraphs', 1, true
from about_pages p where p.page_key = 'scientific-board'
on conflict (page_id, section_key) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'az', 'Şura haqqında'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'scientific-board' and s.section_key = 'about'
on conflict (section_id, lang_code) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'en', 'About the Board'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'scientific-board' and s.section_key = 'about'
on conflict (section_id, lang_code) do nothing;
insert into about_sections (page_id, section_key, section_type, display_order, is_active)
select p.id, 'scientific_council', 'table', 2, true
from about_pages p where p.page_key = 'scientific-board'
on conflict (page_id, section_key) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'az', 'Elmi Şuranın tərkibi'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'scientific-board' and s.section_key = 'scientific_council'
on conflict (section_id, lang_code) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'en', 'Scientific Board Members'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'scientific-board' and s.section_key = 'scientific_council'
on conflict (section_id, lang_code) do nothing;
insert into about_sections (page_id, section_key, section_type, display_order, is_active)
select p.id, 'digital_council', 'table', 3, true
from about_pages p where p.page_key = 'scientific-board'
on conflict (page_id, section_key) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'az', 'Rəqəmsal Şura'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'scientific-board' and s.section_key = 'digital_council'
on conflict (section_id, lang_code) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'en', 'Digital Council'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'scientific-board' and s.section_key = 'digital_council'
on conflict (section_id, lang_code) do nothing;
insert into about_sections (page_id, section_key, section_type, display_order, is_active)
select p.id, 'digital_council_secretariat', 'table', 4, true
from about_pages p where p.page_key = 'scientific-board'
on conflict (page_id, section_key) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'az', 'Katiblik'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'scientific-board' and s.section_key = 'digital_council_secretariat'
on conflict (section_id, lang_code) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'en', 'Secretariat'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'scientific-board' and s.section_key = 'digital_council_secretariat'
on conflict (section_id, lang_code) do nothing;
insert into about_sections (page_id, section_key, section_type, display_order, is_active)
select p.id, 'related', 'links', 5, true
from about_pages p where p.page_key = 'scientific-board'
on conflict (page_id, section_key) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'az', 'Bölmədə daha çox'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'scientific-board' and s.section_key = 'related'
on conflict (section_id, lang_code) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'en', 'More in this section'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'scientific-board' and s.section_key = 'related'
on conflict (section_id, lang_code) do nothing;

-- ── tau ─────────────────────────────────────────────────────────
insert into about_pages (page_key, group_key, template, slug_az, slug_en, display_order, is_active)
values ('tau', 'affiliated', 'entity', 'tau', 'tau', 20, false)
on conflict (page_key) do nothing;
insert into about_page_tr (page_id, lang_code, eyebrow, title, breadcrumb)
select p.id, 'az', 'Bağlı Qurum', 'Türkiyə–Azərbaycan Universiteti', 'TAU'
from about_pages p where p.page_key = 'tau'
on conflict (page_id, lang_code) do nothing;
insert into about_page_tr (page_id, lang_code, eyebrow, title, breadcrumb)
select p.id, 'en', 'Affiliated Entity', 'Türkiye–Azerbaijan University', 'TAU'
from about_pages p where p.page_key = 'tau'
on conflict (page_id, lang_code) do nothing;
insert into about_sections (page_id, section_key, section_type, display_order, is_active)
select p.id, 'about', 'paragraphs', 1, true
from about_pages p where p.page_key = 'tau'
on conflict (page_id, section_key) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'az', 'TAU haqqında'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'tau' and s.section_key = 'about'
on conflict (section_id, lang_code) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'en', 'About TAU'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'tau' and s.section_key = 'about'
on conflict (section_id, lang_code) do nothing;
insert into about_sections (page_id, section_key, section_type, display_order, is_active)
select p.id, 'programmes', 'list', 2, true
from about_pages p where p.page_key = 'tau'
on conflict (page_id, section_key) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'az', 'Təklif edilən proqramlar'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'tau' and s.section_key = 'programmes'
on conflict (section_id, lang_code) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'en', 'Programmes Offered'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'tau' and s.section_key = 'programmes'
on conflict (section_id, lang_code) do nothing;
insert into about_sections (page_id, section_key, section_type, display_order, is_active)
select p.id, 'facts', 'facts', 3, true
from about_pages p where p.page_key = 'tau'
on conflict (page_id, section_key) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'az', 'Qısa məlumat'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'tau' and s.section_key = 'facts'
on conflict (section_id, lang_code) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'en', 'Key Facts'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'tau' and s.section_key = 'facts'
on conflict (section_id, lang_code) do nothing;
insert into about_sections (page_id, section_key, section_type, display_order, is_active)
select p.id, 'related', 'links', 4, true
from about_pages p where p.page_key = 'tau'
on conflict (page_id, section_key) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'az', 'Bölmədə daha çox'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'tau' and s.section_key = 'related'
on conflict (section_id, lang_code) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'en', 'More in this section'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'tau' and s.section_key = 'related'
on conflict (section_id, lang_code) do nothing;

-- ── iit ─────────────────────────────────────────────────────────
insert into about_pages (page_key, group_key, template, slug_az, slug_en, display_order, is_active)
values ('iit', 'affiliated', 'entity', 'iit', 'iit', 21, false)
on conflict (page_key) do nothing;
insert into about_page_tr (page_id, lang_code, eyebrow, title, breadcrumb)
select p.id, 'az', 'Bağlı Qurum', 'İnformasiya Texnologiyaları İnstitutu', 'İTİ'
from about_pages p where p.page_key = 'iit'
on conflict (page_id, lang_code) do nothing;
insert into about_page_tr (page_id, lang_code, eyebrow, title, breadcrumb)
select p.id, 'en', 'Affiliated Entity', 'Institute of Information Technology', 'IIT'
from about_pages p where p.page_key = 'iit'
on conflict (page_id, lang_code) do nothing;
insert into about_sections (page_id, section_key, section_type, display_order, is_active)
select p.id, 'about', 'paragraphs', 1, true
from about_pages p where p.page_key = 'iit'
on conflict (page_id, section_key) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'az', 'İnstitut haqqında'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'iit' and s.section_key = 'about'
on conflict (section_id, lang_code) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'en', 'About the Institute'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'iit' and s.section_key = 'about'
on conflict (section_id, lang_code) do nothing;
insert into about_sections (page_id, section_key, section_type, display_order, is_active)
select p.id, 'related', 'links', 2, true
from about_pages p where p.page_key = 'iit'
on conflict (page_id, section_key) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'az', 'Bölmədə daha çox'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'iit' and s.section_key = 'related'
on conflict (section_id, lang_code) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'en', 'More in this section'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'iit' and s.section_key = 'related'
on conflict (section_id, lang_code) do nothing;

-- ── ics ─────────────────────────────────────────────────────────
insert into about_pages (page_key, group_key, template, slug_az, slug_en, display_order, is_active)
values ('ics', 'affiliated', 'entity', 'ics', 'ics', 22, false)
on conflict (page_key) do nothing;
insert into about_page_tr (page_id, lang_code, eyebrow, title, breadcrumb)
select p.id, 'az', 'Bağlı Qurum', 'İdarəetmə Sistemləri İnstitutu', 'İSİ'
from about_pages p where p.page_key = 'ics'
on conflict (page_id, lang_code) do nothing;
insert into about_page_tr (page_id, lang_code, eyebrow, title, breadcrumb)
select p.id, 'en', 'Affiliated Entity', 'Institute of Control Systems', 'ICS'
from about_pages p where p.page_key = 'ics'
on conflict (page_id, lang_code) do nothing;
insert into about_sections (page_id, section_key, section_type, display_order, is_active)
select p.id, 'about', 'paragraphs', 1, true
from about_pages p where p.page_key = 'ics'
on conflict (page_id, section_key) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'az', 'İnstitut haqqında'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'ics' and s.section_key = 'about'
on conflict (section_id, lang_code) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'en', 'About the Institute'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'ics' and s.section_key = 'about'
on conflict (section_id, lang_code) do nothing;
insert into about_sections (page_id, section_key, section_type, display_order, is_active)
select p.id, 'related', 'links', 2, true
from about_pages p where p.page_key = 'ics'
on conflict (page_id, section_key) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'az', 'Bölmədə daha çox'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'ics' and s.section_key = 'related'
on conflict (section_id, lang_code) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'en', 'More in this section'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'ics' and s.section_key = 'related'
on conflict (section_id, lang_code) do nothing;

-- ── baku-technical-colleges ─────────────────────────────────────
insert into about_pages (page_key, group_key, template, slug_az, slug_en, display_order, is_active)
values ('baku-technical-colleges', 'affiliated', 'entity', 'baku-technical-colleges', 'baku-technical-colleges', 23, false)
on conflict (page_key) do nothing;
insert into about_page_tr (page_id, lang_code, eyebrow, title, breadcrumb)
select p.id, 'az', 'Bağlı Qurum', 'Bakı Texniki Kolleci', 'Bakı Texniki Kolleci'
from about_pages p where p.page_key = 'baku-technical-colleges'
on conflict (page_id, lang_code) do nothing;
insert into about_page_tr (page_id, lang_code, eyebrow, title, breadcrumb)
select p.id, 'en', 'Affiliated Entity', 'Baku Technical College', 'Technical College'
from about_pages p where p.page_key = 'baku-technical-colleges'
on conflict (page_id, lang_code) do nothing;
insert into about_sections (page_id, section_key, section_type, display_order, is_active)
select p.id, 'about', 'paragraphs', 1, true
from about_pages p where p.page_key = 'baku-technical-colleges'
on conflict (page_id, section_key) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'az', 'Kollec haqqında'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'baku-technical-colleges' and s.section_key = 'about'
on conflict (section_id, lang_code) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'en', 'About the College'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'baku-technical-colleges' and s.section_key = 'about'
on conflict (section_id, lang_code) do nothing;
insert into about_sections (page_id, section_key, section_type, display_order, is_active)
select p.id, 'related', 'links', 2, true
from about_pages p where p.page_key = 'baku-technical-colleges'
on conflict (page_id, section_key) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'az', 'Bölmədə daha çox'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'baku-technical-colleges' and s.section_key = 'related'
on conflict (section_id, lang_code) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'en', 'More in this section'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'baku-technical-colleges' and s.section_key = 'related'
on conflict (section_id, lang_code) do nothing;

-- ── baku-state-colleges ─────────────────────────────────────────
insert into about_pages (page_key, group_key, template, slug_az, slug_en, display_order, is_active)
values ('baku-state-colleges', 'affiliated', 'entity', 'baku-state-colleges', 'baku-state-colleges', 24, false)
on conflict (page_key) do nothing;
insert into about_page_tr (page_id, lang_code, eyebrow, title, breadcrumb)
select p.id, 'az', 'Bağlı Qurum', 'Bakı Dövlət Rabitə və Nəqliyyat Kolleci', 'BDRNK'
from about_pages p where p.page_key = 'baku-state-colleges'
on conflict (page_id, lang_code) do nothing;
insert into about_page_tr (page_id, lang_code, eyebrow, title, breadcrumb)
select p.id, 'en', 'Affiliated Entity', 'Baku State College of Communication and Transport', 'Communication College'
from about_pages p where p.page_key = 'baku-state-colleges'
on conflict (page_id, lang_code) do nothing;
insert into about_sections (page_id, section_key, section_type, display_order, is_active)
select p.id, 'about', 'paragraphs', 1, true
from about_pages p where p.page_key = 'baku-state-colleges'
on conflict (page_id, section_key) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'az', 'Kollec haqqında'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'baku-state-colleges' and s.section_key = 'about'
on conflict (section_id, lang_code) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'en', 'About the College'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'baku-state-colleges' and s.section_key = 'about'
on conflict (section_id, lang_code) do nothing;
insert into about_sections (page_id, section_key, section_type, display_order, is_active)
select p.id, 'related', 'links', 2, true
from about_pages p where p.page_key = 'baku-state-colleges'
on conflict (page_id, section_key) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'az', 'Bölmədə daha çox'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'baku-state-colleges' and s.section_key = 'related'
on conflict (section_id, lang_code) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'en', 'More in this section'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'baku-state-colleges' and s.section_key = 'related'
on conflict (section_id, lang_code) do nothing;

-- ── general-policies ────────────────────────────────────────────
insert into about_pages (page_key, group_key, template, slug_az, slug_en, display_order, is_active)
values ('general-policies', 'policies', 'policy_library', 'normativ-senedler/siyaset-senedleri', 'regulatory-documents/policy-documents', 30, false)
on conflict (page_key) do nothing;
insert into about_page_tr (page_id, lang_code, eyebrow, title, breadcrumb)
select p.id, 'az', 'Normativ Sənədlər', 'Ümumi Siyasətlər', 'Ümumi Siyasətlər'
from about_pages p where p.page_key = 'general-policies'
on conflict (page_id, lang_code) do nothing;
insert into about_page_tr (page_id, lang_code, eyebrow, title, breadcrumb)
select p.id, 'en', 'Regulatory Documents', 'General Policies', 'General Policies'
from about_pages p where p.page_key = 'general-policies'
on conflict (page_id, lang_code) do nothing;
insert into about_sections (page_id, section_key, section_type, display_order, is_active)
select p.id, 'categories', 'list', 1, true
from about_pages p where p.page_key = 'general-policies'
on conflict (page_id, section_key) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'az', 'Kateqoriyalar'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'general-policies' and s.section_key = 'categories'
on conflict (section_id, lang_code) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'en', 'Categories'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'general-policies' and s.section_key = 'categories'
on conflict (section_id, lang_code) do nothing;
insert into about_sections (page_id, section_key, section_type, display_order, is_active)
select p.id, 'documents', 'documents', 2, true
from about_pages p where p.page_key = 'general-policies'
on conflict (page_id, section_key) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'az', 'Siyasət sənədləri'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'general-policies' and s.section_key = 'documents'
on conflict (section_id, lang_code) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'en', 'Policy Documents'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'general-policies' and s.section_key = 'documents'
on conflict (section_id, lang_code) do nothing;

-- ── academic-policies ───────────────────────────────────────────
insert into about_pages (page_key, group_key, template, slug_az, slug_en, display_order, is_active)
values ('academic-policies', 'policies', 'policy_pdf', 'academic-policies', 'academic-policies', 31, false)
on conflict (page_key) do nothing;
insert into about_page_tr (page_id, lang_code, eyebrow, title, breadcrumb)
select p.id, 'az', 'Siyasətlər və Sənədlər', 'Akademik Siyasətlər', 'Akademik Siyasətlər'
from about_pages p where p.page_key = 'academic-policies'
on conflict (page_id, lang_code) do nothing;
insert into about_page_tr (page_id, lang_code, eyebrow, title, breadcrumb)
select p.id, 'en', 'Policies & Documents', 'Academic Policies', 'Academic Policies'
from about_pages p where p.page_key = 'academic-policies'
on conflict (page_id, lang_code) do nothing;
insert into about_sections (page_id, section_key, section_type, display_order, is_active)
select p.id, 'document', 'documents', 1, true
from about_pages p where p.page_key = 'academic-policies'
on conflict (page_id, section_key) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'az', 'Sənəd'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'academic-policies' and s.section_key = 'document'
on conflict (section_id, lang_code) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'en', 'Document'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'academic-policies' and s.section_key = 'document'
on conflict (section_id, lang_code) do nothing;

-- ── sustainability-policies ─────────────────────────────────────
insert into about_pages (page_key, group_key, template, slug_az, slug_en, display_order, is_active)
values ('sustainability-policies', 'policies', 'policy_pdf', 'sustainability-policies', 'sustainability-policies', 32, false)
on conflict (page_key) do nothing;
insert into about_page_tr (page_id, lang_code, eyebrow, title, breadcrumb)
select p.id, 'az', 'Siyasətlər və Sənədlər', 'Davamlılıq Siyasətləri', 'Davamlılıq Siyasətləri'
from about_pages p where p.page_key = 'sustainability-policies'
on conflict (page_id, lang_code) do nothing;
insert into about_page_tr (page_id, lang_code, eyebrow, title, breadcrumb)
select p.id, 'en', 'Policies & Documents', 'Sustainability Policies', 'Sustainability Policies'
from about_pages p where p.page_key = 'sustainability-policies'
on conflict (page_id, lang_code) do nothing;
insert into about_sections (page_id, section_key, section_type, display_order, is_active)
select p.id, 'document', 'documents', 1, true
from about_pages p where p.page_key = 'sustainability-policies'
on conflict (page_id, section_key) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'az', 'Sənəd'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'sustainability-policies' and s.section_key = 'document'
on conflict (section_id, lang_code) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'en', 'Document'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'sustainability-policies' and s.section_key = 'document'
on conflict (section_id, lang_code) do nothing;

-- ── procedure-guidelines ────────────────────────────────────────
insert into about_pages (page_key, group_key, template, slug_az, slug_en, display_order, is_active)
values ('procedure-guidelines', 'policies', 'policy_pdf', 'procedure-guidelines', 'procedure-guidelines', 33, false)
on conflict (page_key) do nothing;
insert into about_page_tr (page_id, lang_code, eyebrow, title, breadcrumb)
select p.id, 'az', 'Siyasətlər və Sənədlər', 'Prosedurlar və Qaydalar', 'Prosedurlar və Qaydalar'
from about_pages p where p.page_key = 'procedure-guidelines'
on conflict (page_id, lang_code) do nothing;
insert into about_page_tr (page_id, lang_code, eyebrow, title, breadcrumb)
select p.id, 'en', 'Policies & Documents', 'Procedures & Guidelines', 'Procedures & Guidelines'
from about_pages p where p.page_key = 'procedure-guidelines'
on conflict (page_id, lang_code) do nothing;
insert into about_sections (page_id, section_key, section_type, display_order, is_active)
select p.id, 'document', 'documents', 1, true
from about_pages p where p.page_key = 'procedure-guidelines'
on conflict (page_id, section_key) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'az', 'Sənəd'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'procedure-guidelines' and s.section_key = 'document'
on conflict (section_id, lang_code) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'en', 'Document'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'procedure-guidelines' and s.section_key = 'document'
on conflict (section_id, lang_code) do nothing;

-- ── sustainability-documents ────────────────────────────────────
insert into about_pages (page_key, group_key, template, slug_az, slug_en, display_order, is_active)
values ('sustainability-documents', 'policies', 'policy_library', 'sustainability-documents', 'sustainability-documents', 34, false)
on conflict (page_key) do nothing;
insert into about_page_tr (page_id, lang_code, eyebrow, title, breadcrumb)
select p.id, 'az', 'Normativ Sənədlər', 'Davamlılıq Sənədləri', 'Davamlılıq Sənədləri'
from about_pages p where p.page_key = 'sustainability-documents'
on conflict (page_id, lang_code) do nothing;
insert into about_page_tr (page_id, lang_code, eyebrow, title, breadcrumb)
select p.id, 'en', 'Regulatory Documents', 'Sustainability Documents', 'Sustainability Documents'
from about_pages p where p.page_key = 'sustainability-documents'
on conflict (page_id, lang_code) do nothing;
insert into about_sections (page_id, section_key, section_type, display_order, is_active)
select p.id, 'documents', 'documents', 1, true
from about_pages p where p.page_key = 'sustainability-documents'
on conflict (page_id, section_key) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'az', 'Sənədlər'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'sustainability-documents' and s.section_key = 'documents'
on conflict (section_id, lang_code) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'en', 'Documents'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'sustainability-documents' and s.section_key = 'documents'
on conflict (section_id, lang_code) do nothing;

-- ── accreditation ───────────────────────────────────────────────
insert into about_pages (page_key, group_key, template, slug_az, slug_en, display_order, is_active)
values ('accreditation', 'policies', 'accreditation', 'accreditation', 'accreditation', 35, false)
on conflict (page_key) do nothing;
insert into about_page_tr (page_id, lang_code, eyebrow, title, breadcrumb)
select p.id, 'az', 'Haqqımızda', 'Akkreditasiya', 'Akkreditasiya'
from about_pages p where p.page_key = 'accreditation'
on conflict (page_id, lang_code) do nothing;
insert into about_page_tr (page_id, lang_code, eyebrow, title, breadcrumb)
select p.id, 'en', 'About', 'Accreditation', 'Accreditation'
from about_pages p where p.page_key = 'accreditation'
on conflict (page_id, lang_code) do nothing;
insert into about_sections (page_id, section_key, section_type, display_order, is_active)
select p.id, 'what', 'paragraphs', 1, true
from about_pages p where p.page_key = 'accreditation'
on conflict (page_id, section_key) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'az', 'Akkreditasiya nədir?'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'accreditation' and s.section_key = 'what'
on conflict (section_id, lang_code) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'en', 'What is accreditation?'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'accreditation' and s.section_key = 'what'
on conflict (section_id, lang_code) do nothing;
insert into about_sections (page_id, section_key, section_type, display_order, is_active)
select p.id, 'importance', 'list', 2, true
from about_pages p where p.page_key = 'accreditation'
on conflict (page_id, section_key) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'az', 'Akkreditasiyanın əhəmiyyəti'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'accreditation' and s.section_key = 'importance'
on conflict (section_id, lang_code) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'en', 'Why accreditation matters'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'accreditation' and s.section_key = 'importance'
on conflict (section_id, lang_code) do nothing;
insert into about_sections (page_id, section_key, section_type, display_order, is_active)
select p.id, 'legal', 'list', 3, true
from about_pages p where p.page_key = 'accreditation'
on conflict (page_id, section_key) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'az', 'Hüquqi əsaslar'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'accreditation' and s.section_key = 'legal'
on conflict (section_id, lang_code) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'en', 'Legal basis'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'accreditation' and s.section_key = 'legal'
on conflict (section_id, lang_code) do nothing;
insert into about_sections (page_id, section_key, section_type, display_order, is_active)
select p.id, 'institutional', 'list', 4, true
from about_pages p where p.page_key = 'accreditation'
on conflict (page_id, section_key) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'az', 'İnstitusional akkreditasiya'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'accreditation' and s.section_key = 'institutional'
on conflict (section_id, lang_code) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'en', 'Institutional accreditation'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'accreditation' and s.section_key = 'institutional'
on conflict (section_id, lang_code) do nothing;
insert into about_sections (page_id, section_key, section_type, display_order, is_active)
select p.id, 'institutional_links', 'links', 5, true
from about_pages p where p.page_key = 'accreditation'
on conflict (page_id, section_key) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'az', 'İnstitusional akkreditasiya sənədləri'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'accreditation' and s.section_key = 'institutional_links'
on conflict (section_id, lang_code) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'en', 'Institutional accreditation documents'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'accreditation' and s.section_key = 'institutional_links'
on conflict (section_id, lang_code) do nothing;
insert into about_sections (page_id, section_key, section_type, display_order, is_active)
select p.id, 'program', 'list', 6, true
from about_pages p where p.page_key = 'accreditation'
on conflict (page_id, section_key) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'az', 'Proqram akkreditasiyası'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'accreditation' and s.section_key = 'program'
on conflict (section_id, lang_code) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'en', 'Program accreditation'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'accreditation' and s.section_key = 'program'
on conflict (section_id, lang_code) do nothing;
insert into about_sections (page_id, section_key, section_type, display_order, is_active)
select p.id, 'aqas', 'list', 7, true
from about_pages p where p.page_key = 'accreditation'
on conflict (page_id, section_key) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'az', 'Beynəlxalq akkreditasiya – AQAS'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'accreditation' and s.section_key = 'aqas'
on conflict (section_id, lang_code) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'en', 'International accreditation – AQAS'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'accreditation' and s.section_key = 'aqas'
on conflict (section_id, lang_code) do nothing;
insert into about_sections (page_id, section_key, section_type, display_order, is_active)
select p.id, 'aqas_programs', 'gallery', 8, true
from about_pages p where p.page_key = 'accreditation'
on conflict (page_id, section_key) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'az', 'AQAS akkreditasiyalı proqramlar'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'accreditation' and s.section_key = 'aqas_programs'
on conflict (section_id, lang_code) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'en', 'AQAS-accredited programmes'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'accreditation' and s.section_key = 'aqas_programs'
on conflict (section_id, lang_code) do nothing;
insert into about_sections (page_id, section_key, section_type, display_order, is_active)
select p.id, 'process', 'list', 9, true
from about_pages p where p.page_key = 'accreditation'
on conflict (page_id, section_key) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'az', 'Akkreditasiya prosesi'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'accreditation' and s.section_key = 'process'
on conflict (section_id, lang_code) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'en', 'The accreditation process'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'accreditation' and s.section_key = 'process'
on conflict (section_id, lang_code) do nothing;
insert into about_sections (page_id, section_key, section_type, display_order, is_active)
select p.id, 'reports', 'documents', 10, true
from about_pages p where p.page_key = 'accreditation'
on conflict (page_id, section_key) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'az', 'Proqram akkreditasiyası yekun hesabatları'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'accreditation' and s.section_key = 'reports'
on conflict (section_id, lang_code) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'en', 'Program accreditation final reports'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'accreditation' and s.section_key = 'reports'
on conflict (section_id, lang_code) do nothing;
insert into about_sections (page_id, section_key, section_type, display_order, is_active)
select p.id, 'certificates', 'documents', 11, true
from about_pages p where p.page_key = 'accreditation'
on conflict (page_id, section_key) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'az', 'Proqram akkreditasiyası sertifikatları'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'accreditation' and s.section_key = 'certificates'
on conflict (section_id, lang_code) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'en', 'Program accreditation certificates'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'accreditation' and s.section_key = 'certificates'
on conflict (section_id, lang_code) do nothing;
insert into about_sections (page_id, section_key, section_type, display_order, is_active)
select p.id, 'iso', 'list', 12, true
from about_pages p where p.page_key = 'accreditation'
on conflict (page_id, section_key) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'az', 'ISO standartları'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'accreditation' and s.section_key = 'iso'
on conflict (section_id, lang_code) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'en', 'ISO standards'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'accreditation' and s.section_key = 'iso'
on conflict (section_id, lang_code) do nothing;

-- ── rankings ────────────────────────────────────────────────────
insert into about_pages (page_key, group_key, template, slug_az, slug_en, display_order, is_active)
values ('rankings', 'other', 'rankings', 'reytinqler', 'rankings', 40, false)
on conflict (page_key) do nothing;
insert into about_page_tr (page_id, lang_code, eyebrow, title, breadcrumb)
select p.id, 'az', 'Reytinqlər', 'Beynəlxalq Reytinqlər', 'Reytinqlər'
from about_pages p where p.page_key = 'rankings'
on conflict (page_id, lang_code) do nothing;
insert into about_page_tr (page_id, lang_code, eyebrow, title, breadcrumb)
select p.id, 'en', 'Rankings', 'International Rankings', 'Rankings'
from about_pages p where p.page_key = 'rankings'
on conflict (page_id, lang_code) do nothing;
insert into about_sections (page_id, section_key, section_type, display_order, is_active)
select p.id, 'importance', 'list', 1, true
from about_pages p where p.page_key = 'rankings'
on conflict (page_id, section_key) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'az', 'Əhəmiyyəti'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'rankings' and s.section_key = 'importance'
on conflict (section_id, lang_code) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'en', 'Why rankings matter'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'rankings' and s.section_key = 'importance'
on conflict (section_id, lang_code) do nothing;
insert into about_sections (page_id, section_key, section_type, display_order, is_active)
select p.id, 'systems', 'ranking_systems', 2, true
from about_pages p where p.page_key = 'rankings'
on conflict (page_id, section_key) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'az', 'Reytinq sistemləri'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'rankings' and s.section_key = 'systems'
on conflict (section_id, lang_code) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'en', 'Ranking Systems'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'rankings' and s.section_key = 'systems'
on conflict (section_id, lang_code) do nothing;
insert into about_sections (page_id, section_key, section_type, display_order, is_active)
select p.id, 'positions', 'ranking_positions', 3, true
from about_pages p where p.page_key = 'rankings'
on conflict (page_id, section_key) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'az', 'Beynəlxalq Reytinqlərdə Mövqeyimiz'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'rankings' and s.section_key = 'positions'
on conflict (section_id, lang_code) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'en', 'Our Positions in International Rankings'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'rankings' and s.section_key = 'positions'
on conflict (section_id, lang_code) do nothing;
insert into about_sections (page_id, section_key, section_type, display_order, is_active)
select p.id, 'profile', 'links', 4, true
from about_pages p where p.page_key = 'rankings'
on conflict (page_id, section_key) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'az', 'Universitet profilləri'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'rankings' and s.section_key = 'profile'
on conflict (section_id, lang_code) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'en', 'University Profiles'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'rankings' and s.section_key = 'profile'
on conflict (section_id, lang_code) do nothing;

-- ── hei ─────────────────────────────────────────────────────────
insert into about_pages (page_key, group_key, template, slug_az, slug_en, display_order, is_active)
values ('hei', 'other', 'institute', 'hei', 'hei', 41, false)
on conflict (page_key) do nothing;
insert into about_page_tr (page_id, lang_code, eyebrow, title, breadcrumb)
select p.id, 'az', 'Təhsil və Proqramlar', 'Yüksək Təhsil İnstitutu (YTİ)', 'Yüksək Təhsil İnstitutu'
from about_pages p where p.page_key = 'hei'
on conflict (page_id, lang_code) do nothing;
insert into about_page_tr (page_id, lang_code, eyebrow, title, breadcrumb)
select p.id, 'en', 'Education and Programs', 'Higher Education Institute (HEI)', 'Higher Education Institute'
from about_pages p where p.page_key = 'hei'
on conflict (page_id, lang_code) do nothing;
insert into about_sections (page_id, section_key, section_type, display_order, is_active)
select p.id, 'about', 'paragraphs', 1, true
from about_pages p where p.page_key = 'hei'
on conflict (page_id, section_key) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'az', 'İnstitut haqqında'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'hei' and s.section_key = 'about'
on conflict (section_id, lang_code) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'en', 'About the Institute'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'hei' and s.section_key = 'about'
on conflict (section_id, lang_code) do nothing;
insert into about_sections (page_id, section_key, section_type, display_order, is_active)
select p.id, 'mission', 'paragraphs', 2, true
from about_pages p where p.page_key = 'hei'
on conflict (page_id, section_key) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'az', 'Missiya və strateji istiqamətlər'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'hei' and s.section_key = 'mission'
on conflict (section_id, lang_code) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'en', 'Mission and strategic direction'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'hei' and s.section_key = 'mission'
on conflict (section_id, lang_code) do nothing;
insert into about_sections (page_id, section_key, section_type, display_order, is_active)
select p.id, 'strategic_directions', 'list', 3, true
from about_pages p where p.page_key = 'hei'
on conflict (page_id, section_key) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'az', 'Strateji istiqamətlər'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'hei' and s.section_key = 'strategic_directions'
on conflict (section_id, lang_code) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'en', 'Strategic directions'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'hei' and s.section_key = 'strategic_directions'
on conflict (section_id, lang_code) do nothing;
insert into about_sections (page_id, section_key, section_type, display_order, is_active)
select p.id, 'academic_opportunities', 'list', 4, true
from about_pages p where p.page_key = 'hei'
on conflict (page_id, section_key) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'az', 'Təhsil imkanları'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'hei' and s.section_key = 'academic_opportunities'
on conflict (section_id, lang_code) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'en', 'Academic opportunities'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'hei' and s.section_key = 'academic_opportunities'
on conflict (section_id, lang_code) do nothing;
insert into about_sections (page_id, section_key, section_type, display_order, is_active)
select p.id, 'academic_languages', 'list', 5, true
from about_pages p where p.page_key = 'hei'
on conflict (page_id, section_key) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'az', 'Tədris dilləri'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'hei' and s.section_key = 'academic_languages'
on conflict (section_id, lang_code) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'en', 'Languages of instruction'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'hei' and s.section_key = 'academic_languages'
on conflict (section_id, lang_code) do nothing;
insert into about_sections (page_id, section_key, section_type, display_order, is_active)
select p.id, 'research', 'list', 6, true
from about_pages p where p.page_key = 'hei'
on conflict (page_id, section_key) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'az', 'Elmi-tədqiqat fəaliyyəti'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'hei' and s.section_key = 'research'
on conflict (section_id, lang_code) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'en', 'Research activity'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'hei' and s.section_key = 'research'
on conflict (section_id, lang_code) do nothing;
insert into about_sections (page_id, section_key, section_type, display_order, is_active)
select p.id, 'doctoral', 'paragraphs', 7, true
from about_pages p where p.page_key = 'hei'
on conflict (page_id, section_key) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'az', 'Doktorantura təhsili'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'hei' and s.section_key = 'doctoral'
on conflict (section_id, lang_code) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'en', 'Doctoral studies'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'hei' and s.section_key = 'doctoral'
on conflict (section_id, lang_code) do nothing;
insert into about_sections (page_id, section_key, section_type, display_order, is_active)
select p.id, 'doctoral_formats', 'list', 8, true
from about_pages p where p.page_key = 'hei'
on conflict (page_id, section_key) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'az', 'Doktorantura formaları'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'hei' and s.section_key = 'doctoral_formats'
on conflict (section_id, lang_code) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'en', 'Doctoral study formats'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'hei' and s.section_key = 'doctoral_formats'
on conflict (section_id, lang_code) do nothing;
insert into about_sections (page_id, section_key, section_type, display_order, is_active)
select p.id, 'doctoral_duration', 'group_list', 9, true
from about_pages p where p.page_key = 'hei'
on conflict (page_id, section_key) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'az', 'Təhsil müddəti'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'hei' and s.section_key = 'doctoral_duration'
on conflict (section_id, lang_code) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'en', 'Programme duration'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'hei' and s.section_key = 'doctoral_duration'
on conflict (section_id, lang_code) do nothing;
insert into about_sections (page_id, section_key, section_type, display_order, is_active)
select p.id, 'director', 'people', 10, true
from about_pages p where p.page_key = 'hei'
on conflict (page_id, section_key) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'az', 'Direktor'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'hei' and s.section_key = 'director'
on conflict (section_id, lang_code) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'en', 'Director'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'hei' and s.section_key = 'director'
on conflict (section_id, lang_code) do nothing;
insert into about_sections (page_id, section_key, section_type, display_order, is_active)
select p.id, 'staff', 'people', 11, true
from about_pages p where p.page_key = 'hei'
on conflict (page_id, section_key) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'az', 'Əməkdaşlar'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'hei' and s.section_key = 'staff'
on conflict (section_id, lang_code) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'en', 'Staff'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'hei' and s.section_key = 'staff'
on conflict (section_id, lang_code) do nothing;
insert into about_sections (page_id, section_key, section_type, display_order, is_active)
select p.id, 'contact', 'contact', 12, true
from about_pages p where p.page_key = 'hei'
on conflict (page_id, section_key) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'az', 'Əlaqə'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'hei' and s.section_key = 'contact'
on conflict (section_id, lang_code) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'en', 'Contact'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'hei' and s.section_key = 'contact'
on conflict (section_id, lang_code) do nothing;
insert into about_sections (page_id, section_key, section_type, display_order, is_active)
select p.id, 'board_duties', 'list', 13, true
from about_pages p where p.page_key = 'hei'
on conflict (page_id, section_key) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'az', 'İdarə Heyətinin vəzifələri'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'hei' and s.section_key = 'board_duties'
on conflict (section_id, lang_code) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'en', 'Board duties'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'hei' and s.section_key = 'board_duties'
on conflict (section_id, lang_code) do nothing;
insert into about_sections (page_id, section_key, section_type, display_order, is_active)
select p.id, 'board_rights', 'list', 14, true
from about_pages p where p.page_key = 'hei'
on conflict (page_id, section_key) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'az', 'İdarə Heyətinin hüquqları'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'hei' and s.section_key = 'board_rights'
on conflict (section_id, lang_code) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'en', 'Board rights'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'hei' and s.section_key = 'board_rights'
on conflict (section_id, lang_code) do nothing;
insert into about_sections (page_id, section_key, section_type, display_order, is_active)
select p.id, 'board_composition', 'list', 15, true
from about_pages p where p.page_key = 'hei'
on conflict (page_id, section_key) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'az', 'İdarə Heyətinin tərkibi'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'hei' and s.section_key = 'board_composition'
on conflict (section_id, lang_code) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'en', 'Board composition'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'hei' and s.section_key = 'board_composition'
on conflict (section_id, lang_code) do nothing;
insert into about_sections (page_id, section_key, section_type, display_order, is_active)
select p.id, 'board_requirements', 'list', 16, true
from about_pages p where p.page_key = 'hei'
on conflict (page_id, section_key) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'az', 'İdarə Heyətinin üzvlərinə olan tələblər'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'hei' and s.section_key = 'board_requirements'
on conflict (section_id, lang_code) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'en', 'Requirements for board members'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'hei' and s.section_key = 'board_requirements'
on conflict (section_id, lang_code) do nothing;
insert into about_sections (page_id, section_key, section_type, display_order, is_active)
select p.id, 'board_chairman', 'paragraphs', 17, true
from about_pages p where p.page_key = 'hei'
on conflict (page_id, section_key) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'az', 'İdarə Heyətinin sədri'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'hei' and s.section_key = 'board_chairman'
on conflict (section_id, lang_code) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'en', 'Chair of the Board'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'hei' and s.section_key = 'board_chairman'
on conflict (section_id, lang_code) do nothing;
insert into about_sections (page_id, section_key, section_type, display_order, is_active)
select p.id, 'related', 'links', 18, true
from about_pages p where p.page_key = 'hei'
on conflict (page_id, section_key) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'az', 'Bölmədə daha çox'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'hei' and s.section_key = 'related'
on conflict (section_id, lang_code) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'en', 'More in this section'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'hei' and s.section_key = 'related'
on conflict (section_id, lang_code) do nothing;

-- ── mba ─────────────────────────────────────────────────────────
insert into about_pages (page_key, group_key, template, slug_az, slug_en, display_order, is_active)
values ('mba', 'other', 'programme', 'mba', 'mba', 42, false)
on conflict (page_key) do nothing;
insert into about_page_tr (page_id, lang_code, eyebrow, title, breadcrumb)
select p.id, 'az', 'Təhsil və Proqramlar', 'MBA Proqramı', 'MBA'
from about_pages p where p.page_key = 'mba'
on conflict (page_id, lang_code) do nothing;
insert into about_page_tr (page_id, lang_code, eyebrow, title, breadcrumb)
select p.id, 'en', 'Education and Programs', 'MBA Program', 'MBA'
from about_pages p where p.page_key = 'mba'
on conflict (page_id, lang_code) do nothing;
insert into about_sections (page_id, section_key, section_type, display_order, is_active)
select p.id, 'about', 'paragraphs', 1, true
from about_pages p where p.page_key = 'mba'
on conflict (page_id, section_key) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'az', 'MBA Proqramı Haqqında'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'mba' and s.section_key = 'about'
on conflict (section_id, lang_code) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'en', 'About the MBA Program'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'mba' and s.section_key = 'about'
on conflict (section_id, lang_code) do nothing;
insert into about_sections (page_id, section_key, section_type, display_order, is_active)
select p.id, 'stats', 'stats', 2, true
from about_pages p where p.page_key = 'mba'
on conflict (page_id, section_key) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'az', 'Proqramın Əsas Göstəriciləri'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'mba' and s.section_key = 'stats'
on conflict (section_id, lang_code) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'en', 'Program at a Glance'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'mba' and s.section_key = 'stats'
on conflict (section_id, lang_code) do nothing;
insert into about_sections (page_id, section_key, section_type, display_order, is_active)
select p.id, 'languages', 'list', 3, true
from about_pages p where p.page_key = 'mba'
on conflict (page_id, section_key) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'az', 'Tədris Dilləri'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'mba' and s.section_key = 'languages'
on conflict (section_id, lang_code) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'en', 'Languages of Instruction'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'mba' and s.section_key = 'languages'
on conflict (section_id, lang_code) do nothing;
insert into about_sections (page_id, section_key, section_type, display_order, is_active)
select p.id, 'structure', 'list', 4, true
from about_pages p where p.page_key = 'mba'
on conflict (page_id, section_key) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'az', 'Proqramın Strukturu'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'mba' and s.section_key = 'structure'
on conflict (section_id, lang_code) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'en', 'Program Structure'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'mba' and s.section_key = 'structure'
on conflict (section_id, lang_code) do nothing;
insert into about_sections (page_id, section_key, section_type, display_order, is_active)
select p.id, 'doctoral', 'paragraphs', 5, true
from about_pages p where p.page_key = 'mba'
on conflict (page_id, section_key) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'az', 'Doktorantura İstiqamətləri'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'mba' and s.section_key = 'doctoral'
on conflict (section_id, lang_code) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'en', 'Doctoral Pathways'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'mba' and s.section_key = 'doctoral'
on conflict (section_id, lang_code) do nothing;
insert into about_sections (page_id, section_key, section_type, display_order, is_active)
select p.id, 'doctoral_formats', 'list', 6, true
from about_pages p where p.page_key = 'mba'
on conflict (page_id, section_key) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'az', 'Doktorantura formaları'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'mba' and s.section_key = 'doctoral_formats'
on conflict (section_id, lang_code) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'en', 'Doctoral study formats'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'mba' and s.section_key = 'doctoral_formats'
on conflict (section_id, lang_code) do nothing;
insert into about_sections (page_id, section_key, section_type, display_order, is_active)
select p.id, 'doctoral_duration', 'group_list', 7, true
from about_pages p where p.page_key = 'mba'
on conflict (page_id, section_key) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'az', 'Təhsil Müddəti'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'mba' and s.section_key = 'doctoral_duration'
on conflict (section_id, lang_code) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'en', 'Programme duration'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'mba' and s.section_key = 'doctoral_duration'
on conflict (section_id, lang_code) do nothing;
insert into about_sections (page_id, section_key, section_type, display_order, is_active)
select p.id, 'contact', 'contact', 8, true
from about_pages p where p.page_key = 'mba'
on conflict (page_id, section_key) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'az', 'Əlaqə'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'mba' and s.section_key = 'contact'
on conflict (section_id, lang_code) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'en', 'Contact'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'mba' and s.section_key = 'contact'
on conflict (section_id, lang_code) do nothing;
insert into about_sections (page_id, section_key, section_type, display_order, is_active)
select p.id, 'related', 'links', 9, true
from about_pages p where p.page_key = 'mba'
on conflict (page_id, section_key) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'az', 'Bölmədə daha çox'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'mba' and s.section_key = 'related'
on conflict (section_id, lang_code) do nothing;
insert into about_section_tr (section_id, lang_code, title)
select s.id, 'en', 'More in this section'
from about_sections s join about_pages p on p.id = s.page_id
where p.page_key = 'mba' and s.section_key = 'related'
on conflict (section_id, lang_code) do nothing;

-- =====================================================================
-- VERIFY
-- =====================================================================
-- Expect 24 pages and 98 sections.
select (select count(*) from about_pages)    as pages,
       (select count(*) from about_sections) as sections;

