-- =====================================================================
-- PRODUCTION MIGRATION — About pages ("Haqqımızda" dropdown) CMS
--
-- Turns every /about screen from hard-coded copy in the website's locale
-- files into editable data:
--
--   about_pages                 → the page registry (one row per screen)
--   about_page_tr               → eyebrow / title / subtitle / breadcrumb / SEO
--   about_sections              → ordered typed blocks on a page
--   about_section_tr            → each block's headings and rich-text body
--   about_items                 → ordered rows inside a block
--   about_item_tr               → each row's copy, plus per-language files
--   about_people                → named individuals on the leadership pages
--   about_person_tr             → their name, degree, position, bio
--   about_person_education      → their education history
--   about_person_education_tr   → the degree / institution, per language
--
-- Run in one psql session. Every statement is idempotent and additive.
-- Follow with `python -m app.scripts.seed_about_pages` to create the page
-- registry and each page's section skeleton.
--
-- Pages are seeded with is_active = false on purpose: nothing reaches the
-- public API until an editor explicitly publishes it, so prod never shows a
-- half-filled screen while the content is being typed in.
-- =====================================================================


-- =====================================================================
-- STEP 1 — PAGES
-- =====================================================================
create table if not exists about_pages (
    id             integer generated by default as identity primary key,
    page_key       varchar(100) not null unique,
    group_key      varchar(50)  not null default 'other',
    template       varchar(50)  not null default 'generic',
    slug_az        varchar(255),
    slug_en        varchar(255),
    display_order  integer      not null default 0,
    is_active      boolean      not null default false,
    hero_image     varchar(1024),
    hero_video_url varchar(2048),
    cover_image    varchar(1024),
    pdf_url        varchar(2048),
    pdf_filename   varchar(255),
    website_url    varchar(2048),
    video_url      varchar(2048),
    created_at     timestamptz  not null default current_timestamp,
    updated_at     timestamptz
);
-- The sidebar and the public listing both read in this order.
create index if not exists ix_about_pages_order
    on about_pages (group_key, display_order, id);
create index if not exists ix_about_pages_active
    on about_pages (is_active);

create table if not exists about_page_tr (
    id               integer generated by default as identity primary key,
    page_id          integer not null references about_pages(id) on delete cascade,
    lang_code        varchar(10) not null,
    eyebrow          varchar(255),
    title            varchar(500),
    subtitle         text,
    breadcrumb       varchar(255),
    intro            text,
    meta_title       varchar(500),
    meta_description text,
    created_at       timestamptz not null default current_timestamp,
    updated_at       timestamptz,
    constraint uq_about_page_tr_page_lang unique (page_id, lang_code)
);
create index if not exists ix_about_page_tr_page
    on about_page_tr (page_id, lang_code);


-- =====================================================================
-- STEP 2 — SECTIONS
-- =====================================================================
create table if not exists about_sections (
    id            integer generated by default as identity primary key,
    page_id       integer not null references about_pages(id) on delete cascade,
    section_key   varchar(100) not null,
    -- paragraphs | list | stats | timeline | pillars | people | table |
    -- documents | links | facts | contact | video | quote | gallery |
    -- ranking_systems | ranking_positions | group_list | cards
    section_type  varchar(50)  not null default 'paragraphs',
    display_order integer      not null default 0,
    is_active     boolean      not null default true,
    image_url     varchar(1024),
    link_url      varchar(2048),
    pdf_url       varchar(2048),
    video_url     varchar(2048),
    icon          varchar(100),
    extra         jsonb,
    created_at    timestamptz  not null default current_timestamp,
    updated_at    timestamptz,
    constraint uq_about_sections_page_key unique (page_id, section_key)
);
create index if not exists ix_about_sections_page
    on about_sections (page_id, display_order);

create table if not exists about_section_tr (
    id          integer generated by default as identity primary key,
    section_id  integer not null references about_sections(id) on delete cascade,
    lang_code   varchar(10) not null,
    title       varchar(500),
    subtitle    text,
    description text,
    body_html   text,
    footer      text,
    note        text,
    cta_label   varchar(255),
    pdf_url     varchar(2048),
    headers     jsonb,
    created_at  timestamptz not null default current_timestamp,
    updated_at  timestamptz,
    constraint uq_about_section_tr_section_lang unique (section_id, lang_code)
);
create index if not exists ix_about_section_tr_section
    on about_section_tr (section_id, lang_code);


-- =====================================================================
-- STEP 3 — ITEMS
-- =====================================================================
create table if not exists about_items (
    id            integer generated by default as identity primary key,
    section_id    integer not null references about_sections(id) on delete cascade,
    display_order integer not null default 0,
    item_key      varchar(100),
    is_active     boolean not null default true,
    image_url     varchar(1024),
    link_url      varchar(2048),
    pdf_url       varchar(2048),
    email         varchar(255),
    phone         varchar(100),
    icon          varchar(100),
    slug          varchar(255),
    year          varchar(50),
    num           varchar(50),
    -- Text, not numeric: "476", "851-900", "25,000+", "3 247".
    value         varchar(255),
    extra         jsonb,
    created_at    timestamptz not null default current_timestamp,
    updated_at    timestamptz
);
create index if not exists ix_about_items_section
    on about_items (section_id, display_order);

create table if not exists about_item_tr (
    id          integer generated by default as identity primary key,
    item_id     integer not null references about_items(id) on delete cascade,
    lang_code   varchar(10) not null,
    title       text,
    subtitle    text,
    description text,
    label       varchar(500),
    value_text  varchar(500),
    caption     text,
    link_label  varchar(500),
    -- The policy library ships a separate AZ and EN PDF for the same document.
    file_url    varchar(2048),
    extra       jsonb,
    created_at  timestamptz not null default current_timestamp,
    updated_at  timestamptz,
    constraint uq_about_item_tr_item_lang unique (item_id, lang_code)
);
create index if not exists ix_about_item_tr_item
    on about_item_tr (item_id, lang_code);


-- =====================================================================
-- STEP 4 — PEOPLE
-- =====================================================================
create table if not exists about_people (
    id             integer generated by default as identity primary key,
    section_id     integer not null references about_sections(id) on delete cascade,
    display_order  integer not null default 0,
    is_active      boolean not null default true,
    slug           varchar(255),
    image_url      varchar(1024),
    email          varchar(255),
    phone          varchar(100),
    phone_internal varchar(50),
    room_number    varchar(100),
    created_at     timestamptz not null default current_timestamp,
    updated_at     timestamptz
);
create index if not exists ix_about_people_section
    on about_people (section_id, display_order);
-- Vice-rector detail pages are addressed by slug.
create index if not exists ix_about_people_slug
    on about_people (slug);

create table if not exists about_person_tr (
    id                 integer generated by default as identity primary key,
    person_id          integer not null references about_people(id) on delete cascade,
    lang_code          varchar(10) not null,
    full_name          varchar(500),
    degree             varchar(500),
    position           varchar(500),
    office             varchar(500),
    hours              varchar(255),
    bio_html           text,
    achievements       text,
    -- One interest per line; a plain list of strings with no other attributes.
    research_interests text,
    created_at         timestamptz not null default current_timestamp,
    updated_at         timestamptz,
    constraint uq_about_person_tr_person_lang unique (person_id, lang_code)
);
create index if not exists ix_about_person_tr_person
    on about_person_tr (person_id, lang_code);

create table if not exists about_person_education (
    id            integer generated by default as identity primary key,
    person_id     integer not null references about_people(id) on delete cascade,
    display_order integer not null default 0,
    -- Verbatim "2012-2016": some rows are open-ended and were never split.
    period        varchar(100),
    created_at    timestamptz not null default current_timestamp,
    updated_at    timestamptz
);
create index if not exists ix_about_person_education_person
    on about_person_education (person_id, display_order);

create table if not exists about_person_education_tr (
    id           integer generated by default as identity primary key,
    education_id integer not null references about_person_education(id) on delete cascade,
    lang_code    varchar(10) not null,
    degree       varchar(500),
    institution  varchar(1000),
    created_at   timestamptz not null default current_timestamp,
    updated_at   timestamptz,
    constraint uq_about_person_edu_tr_edu_lang unique (education_id, lang_code)
);
create index if not exists ix_about_person_education_tr_edu
    on about_person_education_tr (education_id, lang_code);


-- =====================================================================
-- STEP 5 — VERIFY
-- =====================================================================
-- Expect 10 rows.
select table_name
from information_schema.tables
where table_schema = 'public'
  and table_name like 'about%'
order by table_name;
