-- =====================================================================
-- MIGRATION — Research: "Seminarlar və Təlimlər" (Seminars & Trainings)
--
-- A new editorial page in the Tədqiqat section (template 'seminars').
-- Reuses the research_pages shape — hero (title + short description), the
-- page's intro text (body_html) and the "More in this section" buttons —
-- and adds one new child:
--   research_page_seminars / _tr → the seminar/training list. Each entry is
--       a bilingual rich-text `name` and a `url` that links to the matching
--       news item on this website. Position is its identity.
--
-- Run AFTER migrations_research_patents.sql. Idempotent and additive.
-- =====================================================================


-- ── STEP 1 — SCHEMA ─────────────────────────────────────────────────────
create table if not exists research_page_seminars (
    id            integer generated by default as identity primary key,
    page_id       integer not null references research_pages(id) on delete cascade,
    url           varchar(2048),
    display_order integer not null default 0,
    created_at    timestamptz not null default current_timestamp,
    updated_at    timestamptz
);
create index if not exists ix_research_page_seminars_page
    on research_page_seminars (page_id, display_order);

create table if not exists research_page_seminar_tr (
    id         integer generated by default as identity primary key,
    seminar_id integer not null references research_page_seminars(id) on delete cascade,
    lang_code  varchar(10) not null,
    name       text,
    created_at timestamptz not null default current_timestamp,
    updated_at timestamptz,
    constraint uq_research_seminar_tr_seminar_lang unique (seminar_id, lang_code)
);
create index if not exists ix_research_page_seminar_tr_seminar
    on research_page_seminar_tr (seminar_id, lang_code);


-- ── STEP 2 — SEED: the page (structure and known chrome only) ───────────
insert into research_pages (page_key, template, slug_az, slug_en, display_order, is_active, created_at)
values ('seminars', 'seminars',
        'tedqiqat/konfranslar-ve-tedbirler/seminarlar-ve-telimler',
        'research/conferences-and-events/seminars-and-trainings', 2, false, current_timestamp)
on conflict (page_key) do nothing;

insert into research_page_tr (page_id, lang_code, title, links_title, created_at)
select p.id, 'az', 'Seminarlar və Təlimlər', 'Bölmədə daha çox', current_timestamp
from research_pages p where p.page_key = 'seminars'
on conflict (page_id, lang_code) do nothing;

insert into research_page_tr (page_id, lang_code, title, links_title, created_at)
select p.id, 'en', 'Seminars and Trainings', 'More in this section', current_timestamp
from research_pages p where p.page_key = 'seminars'
on conflict (page_id, lang_code) do nothing;


-- ── STEP 3 — VERIFY. Expect the seminars page, unpublished, 0 seminars. ──
select p.page_key, p.template, p.is_active,
       (select count(*) from research_page_seminars s where s.page_id = p.id) as seminars
from research_pages p
where p.page_key = 'seminars';
