-- =====================================================================
-- PRODUCTION MIGRATION — Research Projects (Tədqiqat Layihələri)
--
-- Creates the three tables behind the new dashboard module:
--   research_projects          parent — code, cover image, external link
--   research_projects_tr       per-language copy (name, type, duration,
--                              leader, budget, about)
--   research_project_members   ordered team roster (not translated)
--
-- Run the whole file in one psql session against the production DB.
-- Every statement is idempotent: re-running the file is safe, and every
-- change is additive — nothing is dropped or rewritten.
--
-- `id` is declared as an identity column up front, so unlike the older
-- migrations in this repo there is no follow-up sequence-fixing step.
-- =====================================================================


-- =====================================================================
-- STEP 1 — SCHEMA
-- =====================================================================
create table if not exists research_projects (
    id          integer generated by default as identity primary key,
    project_code varchar(50) not null,
    image       varchar(1024),
    project_url varchar(2048),
    created_at  timestamptz not null default now(),
    updated_at  timestamptz
);

-- The FK below targets project_code, which therefore has to be unique.
do $$
begin
    if not exists (
        select 1 from pg_constraint where conname = 'uq_research_projects_code'
    ) then
        alter table research_projects
            add constraint uq_research_projects_code unique (project_code);
    end if;
end $$;

create table if not exists research_projects_tr (
    id           integer generated by default as identity primary key,
    project_code varchar(50) not null
                 references research_projects(project_code) on delete cascade,
    lang_code    varchar(10) not null,
    name         text not null,
    project_type text,
    duration     varchar(255),
    leader_name  varchar(255),
    budget       varchar(255),
    about_html   text,
    created_at   timestamptz not null default now(),
    updated_at   timestamptz,
    constraint uq_research_projects_tr_code_lang unique (project_code, lang_code)
);

create table if not exists research_project_members (
    id            integer generated by default as identity primary key,
    project_code  varchar(50) not null
                  references research_projects(project_code) on delete cascade,
    full_name     varchar(255) not null,
    display_order integer default 0,
    created_at    timestamptz not null default now(),
    updated_at    timestamptz
);

create index if not exists ix_research_projects_tr_code
    on research_projects_tr (project_code);
create index if not exists ix_research_project_members_code
    on research_project_members (project_code);


-- =====================================================================
-- STEP 2 — VERIFY
--
-- Expect the three tables listed, each with an identity `id`.
-- =====================================================================
select table_name,
       (select count(*) from information_schema.columns c
         where c.table_name = t.table_name) as column_count
from information_schema.tables t
where table_name in (
    'research_projects', 'research_projects_tr', 'research_project_members'
)
order by table_name;
