-- =====================================================================
-- MIGRATION — About regulatory-documents: issuing organizations + view metric
--
-- Adds two things to the About "documents" feature:
--
--   1) A new page-scoped entity — document-issuing organizations — mirroring
--      about_doc_categories / about_doc_category_tr exactly, but with a
--      language-neutral logo_url on the parent row. A document references one
--      through its stable, page-local organization_key.
--
--   2) Two columns on about_documents:
--        organization_key — which organization issued the document (or null),
--        view_count       — how many times the public card has been opened; a
--                           metric, never client-set, bumped atomically by the
--                           public POST /api/about/public/documents/{id}/view.
--
-- Language-neutral facts (a key, a logo, an ordering, a counter) live on the
-- row; the translated name lives on the *_tr sibling keyed by lang_code.
--
-- Idempotent and additive: safe to run more than once. Nothing is dropped.
-- =====================================================================


-- ── document-issuing organizations ───────────────────────────────────
create table if not exists about_doc_organizations (
    id               integer generated by default as identity primary key,
    page_id          integer not null references about_pages(id) on delete cascade,
    -- Stable, page-local identifier a document references (e.g. "o-ab12cd").
    organization_key varchar(100) not null,
    -- The organization's logo — an uploaded file's path or a pasted URL.
    logo_url         varchar(2048),
    display_order    integer not null default 0,
    created_at       timestamptz not null default current_timestamp,
    updated_at       timestamptz,
    constraint uq_about_doc_organizations_page_key unique (page_id, organization_key)
);
create index if not exists ix_about_doc_organizations_page
    on about_doc_organizations (page_id, display_order);

create table if not exists about_doc_organization_tr (
    id              integer generated by default as identity primary key,
    organization_id integer not null references about_doc_organizations(id) on delete cascade,
    lang_code       varchar(10) not null,
    name            varchar(500),
    created_at      timestamptz not null default current_timestamp,
    updated_at      timestamptz,
    constraint uq_about_doc_organization_tr_org_lang unique (organization_id, lang_code)
);
create index if not exists ix_about_doc_organization_tr_org
    on about_doc_organization_tr (organization_id, lang_code);


-- ── about_documents: organization reference + view metric ────────────
alter table about_documents
    add column if not exists organization_key varchar(100);
alter table about_documents
    add column if not exists view_count integer not null default 0;


-- ── VERIFY ───────────────────────────────────────────────────────────
select
    (select count(*) from information_schema.tables
       where table_name in ('about_doc_organizations', 'about_doc_organization_tr'))
        as org_tables,               -- expect 2
    (select count(*) from information_schema.columns
       where table_name = 'about_documents'
         and column_name in ('organization_key', 'view_count'))
        as document_columns;         -- expect 2
