-- =====================================================================
-- MIGRATION — About: "Normativ Sənədlər" (Regulatory Documents)
--
-- A document-library section with two pages:
--   policy-documents        (template 'documents')        — has categories
--   sustainability-documents(template 'documents-simple')  — no categories
--
-- Adds two small children, reused by both pages:
--   about_doc_categories / _tr  → the categories a document can belong to,
--       defined once per page. Each has a stable, page-local `category_key`
--       that a document points at. The sustainability page has none.
--   about_documents / _tr       → the document cards. `file_url` is an
--       uploaded file's path or a pasted URL (any format); `category_key`
--       (nullable) ties a card to one of the page's categories.
--
-- Both pages also reuse title + description (short description, rich text).
-- The "search" over documents is a website-side, client-side feature — the
-- backend only needs to store the cards, so there is nothing extra here.
--
-- Run AFTER migrations_about_former_rectors_partners.sql. Idempotent/additive.
-- =====================================================================


-- =====================================================================
-- STEP 1 — SCHEMA
-- =====================================================================
create table if not exists about_doc_categories (
    id            integer generated by default as identity primary key,
    page_id       integer not null references about_pages(id) on delete cascade,
    -- Stable, page-local key a document references (e.g. "c-ab12cd").
    category_key  varchar(100) not null,
    display_order integer not null default 0,
    created_at    timestamptz not null default current_timestamp,
    updated_at    timestamptz,
    constraint uq_about_doc_categories_page_key unique (page_id, category_key)
);
create index if not exists ix_about_doc_categories_page
    on about_doc_categories (page_id, display_order);

create table if not exists about_doc_category_tr (
    id          integer generated by default as identity primary key,
    category_id integer not null references about_doc_categories(id) on delete cascade,
    lang_code   varchar(10) not null,
    name        varchar(500),
    created_at  timestamptz not null default current_timestamp,
    updated_at  timestamptz,
    constraint uq_about_doc_category_tr_cat_lang unique (category_id, lang_code)
);
create index if not exists ix_about_doc_category_tr_cat
    on about_doc_category_tr (category_id, lang_code);

create table if not exists about_documents (
    id            integer generated by default as identity primary key,
    page_id       integer not null references about_pages(id) on delete cascade,
    -- References an about_doc_categories.category_key on the same page, or null.
    category_key  varchar(100),
    -- An uploaded file's path or a pasted URL — any format.
    file_url      varchar(2048),
    display_order integer not null default 0,
    created_at    timestamptz not null default current_timestamp,
    updated_at    timestamptz
);
create index if not exists ix_about_documents_page
    on about_documents (page_id, display_order);

create table if not exists about_document_tr (
    id          integer generated by default as identity primary key,
    document_id integer not null references about_documents(id) on delete cascade,
    lang_code   varchar(10) not null,
    name        varchar(500),
    created_at  timestamptz not null default current_timestamp,
    updated_at  timestamptz,
    constraint uq_about_document_tr_doc_lang unique (document_id, lang_code)
);
create index if not exists ix_about_document_tr_doc
    on about_document_tr (document_id, lang_code);


-- =====================================================================
-- STEP 2 — SEED: the two pages (structure and known chrome only; the
-- categories and documents are entered from the dashboard). Both stay
-- unpublished until an editor publishes them.
-- =====================================================================
insert into about_pages (page_key, template, slug_az, slug_en, display_order, is_active, created_at)
values
  ('policy-documents', 'documents',
   'haqqimizda/normativ-senedler/siyaset-senedleri',
   'about/regulatory-documents/policy-documents', 13, false, current_timestamp),
  ('sustainability-documents', 'documents-simple',
   'haqqimizda/normativ-senedler/dayaniqliliq-senedleri',
   'about/regulatory-documents/sustainability-documents', 14, false, current_timestamp)
on conflict (page_key) do nothing;

insert into about_page_tr (page_id, lang_code, title, links_title, created_at)
select p.id, 'az', 'Siyasət Sənədləri', 'Bölmədə daha çox', current_timestamp
from about_pages p where p.page_key = 'policy-documents'
on conflict (page_id, lang_code) do nothing;

insert into about_page_tr (page_id, lang_code, title, links_title, created_at)
select p.id, 'en', 'Policy Documents', 'More in this section', current_timestamp
from about_pages p where p.page_key = 'policy-documents'
on conflict (page_id, lang_code) do nothing;

insert into about_page_tr (page_id, lang_code, title, links_title, created_at)
select p.id, 'az', 'Dayanıqlılıq Sənədləri', 'Bölmədə daha çox', current_timestamp
from about_pages p where p.page_key = 'sustainability-documents'
on conflict (page_id, lang_code) do nothing;

insert into about_page_tr (page_id, lang_code, title, links_title, created_at)
select p.id, 'en', 'Sustainability Documents', 'More in this section', current_timestamp
from about_pages p where p.page_key = 'sustainability-documents'
on conflict (page_id, lang_code) do nothing;


-- =====================================================================
-- STEP 3 — VERIFY. Expect 2 new pages, unpublished, 0 categories/documents.
-- =====================================================================
select p.page_key, p.template, p.display_order, p.is_active,
       (select count(*) from about_doc_categories c where c.page_id = p.id) as categories,
       (select count(*) from about_documents d where d.page_id = p.id) as documents
from about_pages p
where p.page_key in ('policy-documents', 'sustainability-documents')
order by p.display_order;
