-- =====================================================================
-- PRODUCTION MIGRATION — Cafedra Scientific Activity (Elmi fəaliyyət)
--
-- Run the whole file in one psql session against the production DB.
-- Every statement is idempotent: re-running the file is safe.
--
-- Order matters:
--   STEP 1  schema (tables + columns + indexes)
--   STEP 2  identity/sequences — the new `id` columns are plain integers
--           until this runs, so the first INSERT would fail on a null PK
--   STEP 3  publications seed (optional; migrates the curated static list)
--
-- Take a snapshot/backup before running. STEP 1 and STEP 2 are additive —
-- they add tables and columns and never drop or rewrite existing data.
-- =====================================================================


-- =====================================================================
-- STEP 1 — SCHEMA
-- =====================================================================
alter table cafedras_tr add column if not exists research_areas_intro text;
alter table cafedras_tr add column if not exists projects_grants_intro text;
alter table cafedras_tr add column if not exists publications_intro text;
alter table cafedras_tr add column if not exists industry_cooperation_intro text;
alter table cafedras_tr add column if not exists international_cooperation_intro text;

alter table cafedra_projects add column if not exists url varchar(1024);

alter table cafedra_partner_companies add column if not exists logo_url varchar(1024);
alter table cafedra_partner_companies add column if not exists website_url varchar(1024);

create table if not exists cafedra_scientific_publications (
    id integer primary key,
    cafedra_code varchar(50) not null references cafedras(cafedra_code) on delete cascade,
    publication_index varchar(50) not null,
    quartile varchar(5),
    published_at varchar(50),
    year integer,
    url varchar(2048),
    display_order integer not null default 0,
    created_at timestamptz not null,
    updated_at timestamptz
);

alter table cafedra_scientific_publications add column if not exists year integer;

create index if not exists ix_cafedra_scientific_publications_cafedra_code
    on cafedra_scientific_publications (cafedra_code);

create index if not exists ix_cafedra_scientific_publications_year
    on cafedra_scientific_publications (cafedra_code, year desc, display_order);

create table if not exists cafedra_scientific_publication_tr (
    id integer primary key,
    publication_id integer not null references cafedra_scientific_publications(id) on delete cascade,
    lang_code varchar(10) not null,
    title varchar(1000) not null,
    authors text,
    journal text,
    country varchar(255),
    created_at timestamptz not null,
    updated_at timestamptz,
    constraint uq_cafedra_scientific_publication_tr_id_lang unique (publication_id, lang_code)
);




-- =====================================================================
-- STEP 2 — IDENTITY / SEQUENCES
--
-- Adds GENERATED BY DEFAULT AS IDENTITY to every integer `id` primary key
-- that isn't already an identity, and resyncs each sequence to max(id)+1.
-- Skips columns that already have it, so it is safe to re-run.
-- Without this, INSERT ... RETURNING id on the new tables fails with a
-- null-value-in-column violation.
-- =====================================================================
-- Adds GENERATED BY DEFAULT AS IDENTITY to every `id` column in the public
-- schema that is an integer/bigint primary key and isn't already an identity.
-- Also resyncs the implicit identity sequence to max(id)+1 so future inserts
-- don't collide with rows that were inserted with explicit ids.

do $$
declare
    r record;
    max_id bigint;
    seq_name text;
begin
    for r in
        select c.table_schema,
               c.table_name,
               c.column_name,
               c.data_type
        from information_schema.columns c
        join information_schema.table_constraints tc
          on tc.table_schema = c.table_schema
         and tc.table_name = c.table_name
         and tc.constraint_type = 'PRIMARY KEY'
        join information_schema.key_column_usage kcu
          on kcu.constraint_name = tc.constraint_name
         and kcu.table_schema = tc.table_schema
         and kcu.column_name = c.column_name
        where c.table_schema = 'public'
          and c.column_name = 'id'
          and c.data_type in ('integer', 'bigint')
          and c.is_identity = 'NO'
    loop
        execute format(
            'alter table %I.%I alter column %I drop default',
            r.table_schema, r.table_name, r.column_name
        );

        execute format(
            'alter table %I.%I alter column %I add generated by default as identity',
            r.table_schema, r.table_name, r.column_name
        );

        execute format('select coalesce(max(%I), 0) from %I.%I',
                       r.column_name, r.table_schema, r.table_name)
        into max_id;

        seq_name := pg_get_serial_sequence(
            format('%I.%I', r.table_schema, r.table_name),
            r.column_name
        );

        if seq_name is not null and max_id > 0 then
            execute format('select setval(%L, %s, true)', seq_name, max_id);
        end if;
    end loop;
end $$;


-- =====================================================================
-- STEP 3 — PUBLICATIONS SEED (optional)
--
-- Migrates the curated publication lists that currently live in the
-- website repo at src/data/cafedraPublications.ts. Each cafedra block is
-- skipped when that cafedra already has publications, so re-running is safe.
-- `year` is derived from the free-text date string.
--
-- Run separately:
--   psql "$DATABASE_URL" -f seeds/cafedra_scientific_publications_seed.sql
--
-- Only after verifying the rendered page matches the old static one should
-- src/data/cafedraPublications.ts be deleted from the website repo.
-- =====================================================================
