-- =====================================================================
-- MIGRATION — Home ("Ana səhifə"): landing-page metric strips
--
-- A singleton CMS page (page_key = 'home') carrying two ordered metric
-- lists, told apart by a neutral `group` column ("hero" | "numbers"):
--   * hero    — the compact headline-ranking strip (QS, THE, GreenMetric …)
--   * numbers — the "by the numbers" grid (faculties, students, staff …)
--
-- Each metric's language-neutral facts (value, suffix, ordering) live on
-- the row; the translated label/sublabel live on the `*_tr` sibling keyed
-- by lang_code.
--
-- Seeds the page (is_active = true) and today's 4 hero + 7 numbers metrics
-- so the public API mirrors the current UI immediately. Idempotent: tables
-- use IF NOT EXISTS and the seed is guarded so re-running never duplicates.
-- =====================================================================


-- ── home_pages ───────────────────────────────────────────────────────
create table if not exists home_pages (
    id            integer generated by default as identity primary key,
    page_key      varchar(100) not null unique,
    is_active     boolean not null default false,
    created_at    timestamptz not null default current_timestamp,
    updated_at    timestamptz
);


-- ── home_metrics ─────────────────────────────────────────────────────
create table if not exists home_metrics (
    id            integer generated by default as identity primary key,
    page_id       integer not null references home_pages(id) on delete cascade,
    "group"       varchar(20) not null,
    value         varchar(50),
    suffix        varchar(20),
    display_order integer not null default 0,
    created_at    timestamptz not null default current_timestamp,
    updated_at    timestamptz
);
create index if not exists ix_home_metrics_page
    on home_metrics (page_id, display_order);


-- ── home_metric_tr ───────────────────────────────────────────────────
create table if not exists home_metric_tr (
    id         integer generated by default as identity primary key,
    metric_id  integer not null references home_metrics(id) on delete cascade,
    lang_code  varchar(10) not null,
    label      varchar(500),
    sublabel   varchar(500),
    constraint uq_home_metric_tr_metric_lang unique (metric_id, lang_code)
);
create index if not exists ix_home_metric_tr
    on home_metric_tr (metric_id, lang_code);


-- ── SEED: the singleton page ─────────────────────────────────────────
insert into home_pages (page_key, is_active, created_at, updated_at)
values ('home', true, current_timestamp, current_timestamp)
on conflict (page_key) do nothing;


-- ── SEED: today's metrics (guarded — only when the page has none) ─────
do $$
declare
    v_page_id   integer;
    v_metric_id integer;
begin
    select id into v_page_id from home_pages where page_key = 'home';
    if v_page_id is null then
        return;
    end if;
    -- Re-running never duplicates: seed only when no metric exists yet.
    if exists (select 1 from home_metrics where page_id = v_page_id) then
        return;
    end if;

    -- ── hero strip ────────────────────────────────────────────────────
    insert into home_metrics (page_id, "group", value, suffix, display_order, created_at, updated_at)
    values (v_page_id, 'hero', '801', '+', 0, now(), now()) returning id into v_metric_id;
    insert into home_metric_tr (metric_id, lang_code, label, sublabel) values
        (v_metric_id, 'az', 'QS Reytinqi', null),
        (v_metric_id, 'en', 'QS Ranking', null);

    insert into home_metrics (page_id, "group", value, suffix, display_order, created_at, updated_at)
    values (v_page_id, 'hero', '1501', '+', 1, now(), now()) returning id into v_metric_id;
    insert into home_metric_tr (metric_id, lang_code, label, sublabel) values
        (v_metric_id, 'az', 'THE Reytinqi', null),
        (v_metric_id, 'en', 'THE Ranking', null);

    insert into home_metrics (page_id, "group", value, suffix, display_order, created_at, updated_at)
    values (v_page_id, 'hero', '835', '', 2, now(), now()) returning id into v_metric_id;
    insert into home_metric_tr (metric_id, lang_code, label, sublabel) values
        (v_metric_id, 'az', 'GreenMetric', null),
        (v_metric_id, 'en', 'GreenMetric', null);

    insert into home_metrics (page_id, "group", value, suffix, display_order, created_at, updated_at)
    values (v_page_id, 'hero', '20', '+', 3, now(), now()) returning id into v_metric_id;
    insert into home_metric_tr (metric_id, lang_code, label, sublabel) values
        (v_metric_id, 'az', 'Akkreditasiya', null),
        (v_metric_id, 'en', 'Accreditation', null);

    -- ── numbers grid ──────────────────────────────────────────────────
    insert into home_metrics (page_id, "group", value, suffix, display_order, created_at, updated_at)
    values (v_page_id, 'numbers', '6', '', 0, now(), now()) returning id into v_metric_id;
    insert into home_metric_tr (metric_id, lang_code, label, sublabel) values
        (v_metric_id, 'az', 'Fakültə', 'Akademik bölmələr'),
        (v_metric_id, 'en', 'Faculties', 'Academic divisions');

    insert into home_metrics (page_id, "group", value, suffix, display_order, created_at, updated_at)
    values (v_page_id, 'numbers', '36', '+', 1, now(), now()) returning id into v_metric_id;
    insert into home_metric_tr (metric_id, lang_code, label, sublabel) values
        (v_metric_id, 'az', 'Kafedra', 'Tədris və elmi'),
        (v_metric_id, 'en', 'Departments', 'Teaching and research');

    insert into home_metrics (page_id, "group", value, suffix, display_order, created_at, updated_at)
    values (v_page_id, 'numbers', '126', '+', 2, now(), now()) returning id into v_metric_id;
    insert into home_metric_tr (metric_id, lang_code, label, sublabel) values
        (v_metric_id, 'az', 'İxtisas', 'Bakalavr və magistratura'),
        (v_metric_id, 'en', 'Specialties', 'Bachelor and Master');

    insert into home_metrics (page_id, "group", value, suffix, display_order, created_at, updated_at)
    values (v_page_id, 'numbers', '10000', '+', 3, now(), now()) returning id into v_metric_id;
    insert into home_metric_tr (metric_id, lang_code, label, sublabel) values
        (v_metric_id, 'az', 'Tələbə', 'Aktiv qeydiyyatlı'),
        (v_metric_id, 'en', 'Students', 'Currently enrolled');

    insert into home_metrics (page_id, "group", value, suffix, display_order, created_at, updated_at)
    values (v_page_id, 'numbers', '1000', '+', 4, now(), now()) returning id into v_metric_id;
    insert into home_metric_tr (metric_id, lang_code, label, sublabel) values
        (v_metric_id, 'az', 'Akademik heyət', 'Müəllim və tədqiqatçı'),
        (v_metric_id, 'en', 'Academic staff', 'Lecturers and researchers');

    insert into home_metrics (page_id, "group", value, suffix, display_order, created_at, updated_at)
    values (v_page_id, 'numbers', '150', '+', 5, now(), now()) returning id into v_metric_id;
    insert into home_metric_tr (metric_id, lang_code, label, sublabel) values
        (v_metric_id, 'az', 'Beynəlxalq tərəfdaş', 'Universitet və qurum'),
        (v_metric_id, 'en', 'International partners', 'Universities and institutions');

    insert into home_metrics (page_id, "group", value, suffix, display_order, created_at, updated_at)
    values (v_page_id, 'numbers', '100', '+', 6, now(), now()) returning id into v_metric_id;
    insert into home_metric_tr (metric_id, lang_code, label, sublabel) values
        (v_metric_id, 'az', 'Laboratoriya', 'Tədqiqat və tədris'),
        (v_metric_id, 'en', 'Laboratories', 'Research and teaching');
end $$;


-- ── VERIFY ───────────────────────────────────────────────────────────
select
    (select count(*) from home_pages   where page_key = 'home')                                        as home_pages,
    (select count(*) from home_metrics  m join home_pages p on p.id = m.page_id where p.page_key = 'home' and m."group" = 'hero')    as hero_metrics,
    (select count(*) from home_metrics  m join home_pages p on p.id = m.page_id where p.page_key = 'home' and m."group" = 'numbers') as number_metrics,
    (select count(*) from home_metric_tr t join home_metrics m on m.id = t.metric_id join home_pages p on p.id = m.page_id where p.page_key = 'home') as metric_tr_rows;
