-- =====================================================================
-- MIGRATION — About: "Rektor" (Rector)
--
-- Adds:
--   about_pages.experience / .email / .image_url  → the hero facts that
--       read the same in every language: "30+ Years", the address, the
--       portrait (an uploaded file or a pasted URL)
--   about_page_tr.degree / .position              → the two hero stat
--       values, per language ("Technical Sciences", "Professor")
--   about_page_tr.message / .about                → the rector's message
--       and the "About the rector" biography, both rich text
--   about_images / _tr-less                        → the gallery strip
--   the `rector` page itself
--
-- Why a new `rector` template rather than reusing an existing one: the
-- page is a person, not a set of statement cards or a timeline. It has a
-- portrait, a degree and a title, a long message, a biography, a list of
-- offices that report to the rector, and a photo gallery — a shape none
-- of the other About pages share. The `template` column lets the
-- dashboard show the right form and the website pick the right renderer.
--
-- Why `experience`, `email` and `image_url` sit on the page row and not
-- on `about_page_tr`: an email, a portrait and "30+ Years" are the same
-- in Azerbaijani and English, exactly like `document_url`.
--
-- Why the offices reuse `about_lists` (list_key = 'offices') instead of a
-- new table: an office is a plain, ordered, bilingual name with no
-- attributes of its own — the same shape as the Strategic Plan's values
-- and KPIs, which `about_lists` already stores as a JSONB string array.
--
-- Why `about_images` has no `*_tr` sibling: a photo is language-neutral.
--
-- Run AFTER migrations_about_strategic_plan.sql. Idempotent and additive.
-- =====================================================================


-- =====================================================================
-- STEP 1 — SCHEMA
-- =====================================================================
alter table about_pages
    add column if not exists experience varchar(100);
alter table about_pages
    add column if not exists email      varchar(255);
alter table about_pages
    add column if not exists image_url  varchar(2048);

alter table about_page_tr
    add column if not exists degree   varchar(255);
alter table about_page_tr
    add column if not exists position varchar(255);
alter table about_page_tr
    add column if not exists message  text;
alter table about_page_tr
    add column if not exists about    text;

create table if not exists about_images (
    id            integer generated by default as identity primary key,
    page_id       integer not null references about_pages(id) on delete cascade,
    -- An uploaded file's path ("static/about/images/…") or a pasted URL.
    image_url     varchar(2048) not null,
    display_order integer not null default 0,
    created_at    timestamptz not null default current_timestamp,
    updated_at    timestamptz
);
create index if not exists ix_about_images_page
    on about_images (page_id, display_order);


-- =====================================================================
-- STEP 2 — SEED: the Rector page
--
-- The known hero facts are seeded so the page is meaningful out of the
-- box; the message, biography, offices and gallery are entered from the
-- dashboard. The page stays unpublished until an editor publishes it.
-- =====================================================================
insert into about_pages (page_key, template, slug_az, slug_en, experience, email, display_order, is_active)
values ('rector', 'rector',
        'haqqimizda/rehbetlik-ve-idareetme/rektor',
        'about/leadership-and-management/rector',
        '30+ Years', 'rector@aztu.edu.az',
        4, false)
on conflict (page_key) do nothing;

insert into about_page_tr (page_id, lang_code, title, degree, position, links_title)
select p.id, 'az', 'Vilayət Vəliyev', 'Texniki elmlər', 'Professor', 'Bölmədə daha çox'
from about_pages p where p.page_key = 'rector'
on conflict (page_id, lang_code) do nothing;

insert into about_page_tr (page_id, lang_code, title, degree, position, links_title)
select p.id, 'en', 'Vilayat Valiyev', 'Technical Sciences', 'Professor', 'More in this section'
from about_pages p where p.page_key = 'rector'
on conflict (page_id, lang_code) do nothing;

-- The offices list the page renders. Numbered on the website, so 'number'.
insert into about_lists (page_id, list_key, style, display_order)
select p.id, 'offices', 'number', 1
from about_pages p where p.page_key = 'rector'
on conflict (page_id, list_key) do nothing;

insert into about_list_tr (list_id, lang_code, title)
select l.id, v.lang, v.title
from about_lists l
join about_pages p on p.id = l.page_id
join (values ('offices', 'az', 'Rektora tabe olan bölmələr'),
             ('offices', 'en', 'Offices reporting to the Rector')
     ) as v(k, lang, title) on v.k = l.list_key
where p.page_key = 'rector'
on conflict (list_id, lang_code) do nothing;


-- =====================================================================
-- STEP 3 — VERIFY. Expect the rector page with template 'rector' and its
-- single 'offices' list.
-- =====================================================================
select p.page_key, p.template, p.is_active, p.experience, p.email,
       (select count(*) from about_lists  l where l.page_id = p.id) as lists,
       (select count(*) from about_images i where i.page_id = p.id) as images
from about_pages p
order by p.display_order;
