"""init

Revision ID: d0b0cd24db8e
Revises: 
Create Date: 2026-01-22 02:00:07.566546

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd0b0cd24db8e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('collaboration_translation')
    op.drop_table('collaboration')
    op.create_index(op.f('ix_announcement_id'), 'announcement', ['id'], unique=False)
    op.create_index(op.f('ix_announcement_translation_id'), 'announcement_translation', ['id'], unique=False)
    op.create_index(op.f('ix_news_id'), 'news', ['id'], unique=False)
    op.create_index(op.f('ix_news_category_id'), 'news_category', ['id'], unique=False)
    op.create_index(op.f('ix_news_category_translation_id'), 'news_category_translation', ['id'], unique=False)
    op.create_index(op.f('ix_news_gallery_id'), 'news_gallery', ['id'], unique=False)
    op.create_index(op.f('ix_news_translation_id'), 'news_translation', ['id'], unique=False)
    op.alter_column('project', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('project', 'project_id',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('project', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('project', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_index(op.f('ix_project_id'), 'project', ['id'], unique=False)
    op.alter_column('project_translation', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('project_translation', 'project_id',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('project_translation', 'html_content',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.create_index(op.f('ix_project_translation_id'), 'project_translation', ['id'], unique=False)
    op.drop_constraint('project_fk', 'project_translation', type_='foreignkey')
    op.create_foreign_key(None, 'project_translation', 'project', ['project_id'], ['project_id'])
    op.create_index(op.f('ix_slider_id'), 'slider', ['id'], unique=False)
    op.create_index(op.f('ix_slider_translation_id'), 'slider_translation', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_slider_translation_id'), table_name='slider_translation')
    op.drop_index(op.f('ix_slider_id'), table_name='slider')
    op.drop_constraint(None, 'project_translation', type_='foreignkey')
    op.create_foreign_key('project_fk', 'project_translation', 'project', ['project_id'], ['project_id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_project_translation_id'), table_name='project_translation')
    op.alter_column('project_translation', 'html_content',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('project_translation', 'project_id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('project_translation', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_project_id'), table_name='project')
    op.alter_column('project', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('project', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('project', 'project_id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('project', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_news_translation_id'), table_name='news_translation')
    op.drop_index(op.f('ix_news_gallery_id'), table_name='news_gallery')
    op.drop_index(op.f('ix_news_category_translation_id'), table_name='news_category_translation')
    op.drop_index(op.f('ix_news_category_id'), table_name='news_category')
    op.drop_index(op.f('ix_news_id'), table_name='news')
    op.drop_index(op.f('ix_announcement_translation_id'), table_name='announcement_translation')
    op.drop_index(op.f('ix_announcement_id'), table_name='announcement')
    op.create_table('collaboration',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('collaboration_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('display_order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('image', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='collaboration_pkey'),
    sa.UniqueConstraint('collaboration_id', name='collaboration_collaboration_id_key', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('collaboration_translation',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('collaboration_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('lang_code', sa.VARCHAR(length=2), autoincrement=False, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.CheckConstraint("lang_code::text = ANY (ARRAY['az'::character varying, 'en'::character varying]::text[])", name='chk_lang_code'),
    sa.PrimaryKeyConstraint('id', name='collaboration_translation_pkey'),
    sa.UniqueConstraint('collaboration_id', 'lang_code', name='uq_collaboration_lang', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
