from app.services.search.service import (
    SUPPORTED_LANGS,
    DOC_TYPES,
    ensure_indices,
    search,
    reindex_news,
    reindex_announcement,
    reindex_project,
    reindex_collaboration,
    reindex_faculty,
    reindex_cafedra,
    reindex_department,
    reindex_employee,
    reindex_research_institute,
    delete_doc_by_type,
    on_news_change, on_news_delete,
    on_announcement_change, on_announcement_delete,
    on_project_change, on_project_delete,
    on_collaboration_change, on_collaboration_delete,
    on_faculty_change, on_faculty_delete,
    on_cafedra_change, on_cafedra_delete,
    on_department_change, on_department_delete,
    on_employee_change, on_employee_delete,
    on_research_institute_change, on_research_institute_delete,
)

__all__ = [
    "SUPPORTED_LANGS",
    "DOC_TYPES",
    "ensure_indices",
    "search",
    "reindex_news",
    "reindex_announcement",
    "reindex_project",
    "reindex_collaboration",
    "reindex_faculty",
    "reindex_cafedra",
    "reindex_department",
    "reindex_employee",
    "reindex_research_institute",
    "delete_doc_by_type",
    "on_news_change", "on_news_delete",
    "on_announcement_change", "on_announcement_delete",
    "on_project_change", "on_project_delete",
    "on_collaboration_change", "on_collaboration_delete",
    "on_faculty_change", "on_faculty_delete",
    "on_cafedra_change", "on_cafedra_delete",
    "on_department_change", "on_department_delete",
    "on_employee_change", "on_employee_delete",
    "on_research_institute_change", "on_research_institute_delete",
]
